<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/b/bi12bsetm.css';
import '../../css/i/i9d305b6c.css';
import '../../css/f/fqtl0s-nb.css';
import '../../css/e/en5ob8o0b.css';
import '../../css/c/csts02bkt.css';
import '../../css/i/idrq46bcp.css';
import '../../css/r/r2wo8gvvd.css';
import '../../css/i/isfwp1bvw.css';
import '../../css/a/ahrkdjy4u.css';
import '../../css/b/bcxzoxbcy.css';
import '../../css/x/xsai7fb6g.css';
import '../../css/b/bqfahrkyw.css';
import '../../css/w/wkorq-bhj.css';
import '../../css/f/fzbus2b4r.css';
import '../../css/i/iwviw9n_m.css';
import '../../css/z/zhjl5iqyr.css';
import '../../css/p/pe8x6dbud.css';
import '../../css/w/w42toeb7a.css';
import '../../css/x/xw-d4ibpu.css';
import '../../css/p/p_mp66fqp.css';
import '../../css/a/arrik7peh.css';
import '../../css/w/wxz9-wbzz.css';
import '../../css/a/ak7stibfd.css';
import '../../css/v/v11psvewe.css';
import '../../css/n/noti9cb9b.css';
import '../../css/t/t0hrccb5a.css';
import '../../css/y/ydivzrb1n.css';
import '../../css/j/jkr10o0co.css';
import '../../css/d/dcgm7wbln.css';
import '../../css/h/ho5f_bbnb.css';
import '../../css/s/sebu6eb5y.css';
import '../../css/u/uen0svm_k.css';
import '../../css/h/h2fmn8_tc.css';
import '../../css/k/k-qxy0_yn.css';
import '../../css/i/ihk-mj8te.css';
import '../../css/j/jhzqbr7at.css';
import '../../css/e/e6lp8qb6n.css';
import '../../css/r/r0c2tetao.css';
import '../../css/g/gnsn9pa7e.css';
import '../../css/z/z3n_jobkc.css';
import '../../css/z/zmg5ag4kn.css';
import '../../css/q/qplc839zm.css';
import '../../css/y/ywtir_00b.css';
import '../../css/v/vave9972g.css';
import '../../css/z/z49ff3bsg.css';
import '../../css/r/rhm4tebhd.css';
import '../../css/l/lkk8b6dmp.css';
import '../../css/w/w3uh3jurg.css';
import '../../css/c/ch2wy4b9k.css';
import '../../css/k/klbe78m4o.css';
import '../../css/u/u75ay20uo.css';
import '../../css/y/yyyn3ugej.css';
import '../../css/g/gkbubsb3o.css';
import '../../css/m/mp1gdjbou.css';
import '../../css/g/g3e0ynw5o.css';
import '../../css/o/oze2dccaj.css';
import '../../css/l/l93fuvtsx.css';
import '../../css/w/wiggwjb1z.css';
import '../../css/t/tcu8djbst.css';
import '../../css/e/ecrw0tsgi.css';
import '../../css/u/u7rib3b7f.css';
import '../../css/a/ahm4tqb1p.css';
import '../../css/n/nq-_tbbgf.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":301,"height":151};
const content = `<g class="bi12bsetm"><path class="i9d305b6c"/><path class="fqtl0s-nb"/><path class="en5ob8o0b"/><path class="csts02bkt"/><path class="idrq46bcp"/><path class="r2wo8gvvd"/><path class="isfwp1bvw"/><path class="ahrkdjy4u"/><path class="bcxzoxbcy"/><path class="xsai7fb6g"/><path class="bqfahrkyw"/><path class="wkorq-bhj"/><path class="fzbus2b4r"/><path class="iwviw9n_m"/><path class="zhjl5iqyr"/><path class="pe8x6dbud"/><path class="w42toeb7a"/><path class="xw-d4ibpu"/><path class="p_mp66fqp"/><path class="arrik7peh"/><path class="wxz9-wbzz"/><path class="ak7stibfd"/><path class="v11psvewe"/><path class="noti9cb9b"/><path class="t0hrccb5a"/><path class="ydivzrb1n"/><path class="jkr10o0co"/><path class="dcgm7wbln"/><path class="ho5f_bbnb"/><path class="sebu6eb5y"/><path class="uen0svm_k"/><path class="h2fmn8_tc"/><path class="k-qxy0_yn"/><path class="ihk-mj8te"/><path class="jhzqbr7at"/><path class="e6lp8qb6n"/><path class="r0c2tetao"/><path class="gnsn9pa7e"/><path class="z3n_jobkc"/><path class="zmg5ag4kn"/><path class="qplc839zm"/><path class="ywtir_00b"/><path class="vave9972g"/><path class="z49ff3bsg"/><path class="rhm4tebhd"/><path class="lkk8b6dmp"/><path class="w3uh3jurg"/><path class="ch2wy4b9k"/><path class="klbe78m4o"/><path class="u75ay20uo"/><path class="yyyn3ugej"/><path class="gkbubsb3o"/><path class="mp1gdjbou"/><path class="g3e0ynw5o"/><path class="oze2dccaj"/><path class="l93fuvtsx"/><path class="wiggwjb1z"/><path class="tcu8djbst"/><path class="ecrw0tsgi"/><path class="u7rib3b7f"/><path class="ahm4tqb1p"/><path class="nq-_tbbgf"/></g>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="cif:hr" /></template>
