<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/k/k05n1gbkm.css';
import '../../css/w/w0nl4mfrq.css';
import '../../css/r/ruaue58hw.css';
import '../../css/i/i_8iqmb0z.css';
import '../../css/a/agq5extxc.css';
import '../../css/p/pn7pd_a_c.css';
import '../../css/a/a8-updb-w.css';
import '../../css/s/sde8bid2d.css';
import '../../css/k/kmw-5ce2l.css';
import '../../css/o/opgnp9rna.css';
import '../../css/f/f9qhwgbzx.css';
import '../../css/k/kr-09eboz.css';
import '../../css/s/she65ac6d.css';
import '../../css/w/wk1loj6jn.css';
import '../../css/q/qbqkj5u9f.css';
import '../../css/e/ezp2cl61v.css';
import '../../css/k/k7ygktcyp.css';
import '../../css/t/tpzrw1vza.css';
import '../../css/k/kyznz5pqw.css';
import '../../css/s/sy_gfq40q.css';
import '../../css/y/yenoxibpl.css';
import '../../css/q/q4as12-wu.css';
import '../../css/w/wo60yyxlp.css';
import '../../css/z/zpdzwlrtw.css';
import '../../css/j/j-_nbgb8z.css';
import '../../css/a/a_jx0jb_k.css';
import '../../css/v/vhpq4-bzu.css';
import '../../css/o/ouyswbc0t.css';
import '../../css/q/qcmii1bow.css';
import '../../css/l/lqxvo2bjw.css';
import '../../css/l/lnfhfmb8r.css';
import '../../css/f/fsmnxccxz.css';
import '../../css/v/vbygvc10b.css';
import '../../css/e/e4q6n_bsv.css';
import '../../css/v/vlybygv3i.css';
import '../../css/z/zfx6--g2v.css';
import '../../css/m/mzkf_gbse.css';
import '../../css/g/g786bubhr.css';
import '../../css/x/xeest-brn.css';
import '../../css/t/tlt_zybav.css';
import '../../css/m/ml7ab85-j.css';
import '../../css/s/s24vo9bjp.css';
import '../../css/j/jwjkdlfxi.css';
import '../../css/g/gynymwbwa.css';
import '../../css/j/j9t37vbzd.css';
import '../../css/t/tlftqxb2v.css';
import '../../css/a/ajxps9bkj.css';
import '../../css/o/ohh0hfbnz.css';
import '../../css/o/oo3034kae.css';
import '../../css/u/ukpy2bbul.css';
import '../../css/m/mq_k8lbhw.css';
import '../../css/g/gnyw9rzqc.css';
import '../../css/k/kq6qwgb_t.css';
import '../../css/f/f-jd-wbjd.css';
import '../../css/v/vqh0g8q7z.css';
import '../../css/t/t7up_4byu.css';
import '../../css/h/h6b66rb4a.css';
import '../../css/w/w-4n60b2m.css';
import '../../css/r/ra0oasszl.css';
import '../../css/y/y1vsebksf.css';
import '../../css/e/e6psvcbbv.css';
import '../../css/b/bkdsinfgz.css';
import '../../css/w/wf3nm2baf.css';
import '../../css/n/nr3pi7bog.css';
import '../../css/h/hwtxitb8q.css';
import '../../css/q/qjlu6y0fy.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":256,"height":193};
const content = `<defs><linearGradient id="SVG4Q3Hhctf" x1="49.4%" x2="50.3%" y1="49.5%" y2="50.4%"><stop offset="0%"/><stop offset="100%" class="k05n1gbkm"/></linearGradient><linearGradient id="SVGgxghOQ8d" x1="50.1%" x2="49.9%" y1="49.9%" y2="50.1%"><stop offset="0%"/><stop offset="100%" class="k05n1gbkm"/></linearGradient><linearGradient id="SVGBPkKncBt" x1="81.5%" x2="93.7%" y1="46.5%" y2="50.2%"><stop offset="0%" class="w0nl4mfrq"/><stop offset="44.4%" class="ruaue58hw"/><stop offset="64.1%" class="i_8iqmb0z"/><stop offset="100%" class="agq5extxc"/></linearGradient><linearGradient id="SVGosLlFk4t" x1="63.5%" x2="41.4%" y1="61.3%" y2="43.4%"><stop offset="0%" class="pn7pd_a_c"/><stop offset="100%" class="a8-updb-w"/></linearGradient><linearGradient id="SVG0QVTScIK" x1="50.9%" x2="49.2%" y1="51.1%" y2="49.3%"><stop offset="0%" class="sde8bid2d"/><stop offset="13.3%" class="kmw-5ce2l"/><stop offset="29.4%" class="opgnp9rna"/><stop offset="50.2%" class="f9qhwgbzx"/><stop offset="69.7%" class="kr-09eboz"/><stop offset="86.3%" class="she65ac6d"/><stop offset="100%" class="wk1loj6jn"/></linearGradient><linearGradient id="SVGQosi6dAV" x1="47.4%" x2="22.3%" y1="28.9%" y2="77.5%"><stop offset="8.8%" class="qbqkj5u9f"/><stop offset="48.3%" class="ezp2cl61v"/><stop offset="77.9%" class="k7ygktcyp"/></linearGradient><linearGradient id="SVG0Qx6sbdZ" x1="41.1%" x2="56.6%" y1="57.3%" y2="45%"><stop offset="3.3%" class="a8-updb-w"/><stop offset="100%" class="pn7pd_a_c"/></linearGradient><linearGradient id="SVGkwQu5MNZ" x1="49.6%" x2="50.7%" y1="50.5%" y2="49.2%"><stop offset="0%" class="tpzrw1vza"/><stop offset="8.6%" class="kyznz5pqw"/><stop offset="19.8%" class="sy_gfq40q"/><stop offset="58.3%" class="yenoxibpl"/><stop offset="77.7%" class="a8-updb-w"/><stop offset="92.4%" class="q4as12-wu"/></linearGradient><linearGradient id="SVGdMRYsc1p" x1="8.2%" x2="93.2%" y1="50%" y2="50%"><stop offset="0%" class="wo60yyxlp"/><stop offset="49.3%" class="zpdzwlrtw"/><stop offset="50%" class="zpdzwlrtw"/><stop offset="53%" class="j-_nbgb8z"/><stop offset="100%" class="wo60yyxlp"/></linearGradient><linearGradient id="SVGr1zn4bcK" x1="49.9%" x2="50%" y1="50.1%" y2="50%"><stop offset="0%" class="a_jx0jb_k"/><stop offset="24%" class="vhpq4-bzu"/><stop offset="100%" class="ouyswbc0t"/></linearGradient><linearGradient id="SVG9qyHlbld" x1="51.4%" x2="48.7%" y1="48.2%" y2="51.6%"><stop offset="4.8%" class="qcmii1bow"/><stop offset="41.6%" class="lqxvo2bjw"/><stop offset="81.3%" class="lnfhfmb8r"/></linearGradient><linearGradient id="SVGe6dSDd6f" x1="63%" x2="25%" y1="46.8%" y2="8.9%"><stop offset="0%" class="fsmnxccxz"/><stop offset="43.1%" class="vbygvc10b"/><stop offset="44.1%" class="e4q6n_bsv"/><stop offset="87.4%" class="vlybygv3i"/><stop offset="100%" class="zfx6--g2v"/></linearGradient><linearGradient id="SVGJGhfjbAA" x1="50%" x2="50.1%" y1="50%" y2="50.1%"><stop offset="0%" class="ouyswbc0t"/><stop offset="100%" class="a_jx0jb_k"/></linearGradient><linearGradient id="SVGcmultcKp" x1="45.7%" x2="50.5%" y1="62.6%" y2="33.5%"><stop offset="0%" class="mzkf_gbse"/><stop offset="38.6%" class="g786bubhr"/><stop offset="45.6%" class="xeest-brn"/><stop offset="62.4%" class="mzkf_gbse"/><stop offset="100%" class="tlt_zybav"/></linearGradient></defs><path fill="url(#SVG4Q3Hhctf)" class="ml7ab85-j"/><path fill="url(#SVGgxghOQ8d)" class="s24vo9bjp"/><path class="jwjkdlfxi"/><path fill="url(#SVGBPkKncBt)" class="gynymwbwa"/><path fill="url(#SVGosLlFk4t)" class="j9t37vbzd"/><path fill="url(#SVG0QVTScIK)" class="tlftqxb2v"/><path class="ajxps9bkj"/><path fill="url(#SVGQosi6dAV)" class="ohh0hfbnz"/><path fill="url(#SVG0Qx6sbdZ)" class="oo3034kae"/><path fill="url(#SVGkwQu5MNZ)" class="ukpy2bbul"/><path fill="url(#SVGdMRYsc1p)" class="mq_k8lbhw"/><path class="gnyw9rzqc"/><path class="kq6qwgb_t"/><path fill="url(#SVGr1zn4bcK)" class="f-jd-wbjd"/><path class="vqh0g8q7z"/><path fill="url(#SVG9qyHlbld)" class="t7up_4byu"/><path class="h6b66rb4a"/><path fill="url(#SVGe6dSDd6f)" class="w-4n60b2m"/><path class="ra0oasszl"/><path class="y1vsebksf"/><path class="e6psvcbbv"/><path fill="url(#SVGJGhfjbAA)" class="bkdsinfgz"/><path class="wf3nm2baf"/><path class="nr3pi7bog"/><path fill="url(#SVGcmultcKp)" class="hwtxitb8q"/><path class="qjlu6y0fy"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="thesvg-color:parcel" /></template>
