<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/b/bi12bsetm.css';
import '../../css/t/tqs3vpmmc.css';
import '../../css/n/nxdg8xz_g.css';
import '../../css/v/v0kp6pbgp.css';
import '../../css/t/tyi647blx.css';
import '../../css/t/ti56t1b-y.css';
import '../../css/h/heq9_lbrw.css';
import '../../css/i/ilvd6gbst.css';
import '../../css/a/ayqmttbwe.css';
import '../../css/w/w--ylccjk.css';
import '../../css/e/eclqd1smr.css';
import '../../css/f/f1ej4sbit.css';
import '../../css/n/n61v_wt5g.css';
import '../../css/c/c62diobmw.css';
import '../../css/e/evq528j_k.css';
import '../../css/j/j657qptmb.css';
import '../../css/n/nbfk9ubyf.css';
import '../../css/u/uw8axu5xi.css';
import '../../css/t/ts4l8vbsa.css';
import '../../css/h/h5n7eurdv.css';
import '../../css/o/o7ep6_bnw.css';
import '../../css/m/m1r4_nb0f.css';
import '../../css/o/olt1ugbdv.css';
import '../../css/m/my8yrzb5a.css';
import '../../css/o/o1755xbbx.css';
import '../../css/i/iweh6ybyd.css';
import '../../css/b/bj8fdkb3d.css';
import '../../css/n/n01p3bb8p.css';
import '../../css/j/jjwv42bdh.css';
import '../../css/j/jb6q9ybou.css';
import '../../css/a/aoqwfravp.css';
import '../../css/j/jgrkhh1ha.css';
import '../../css/l/lm25pybxy.css';
import '../../css/m/mh911mq2u.css';
import '../../css/j/j012-xb-x.css';
import '../../css/v/vs7ba7bqx.css';
import '../../css/q/qt5hwrlbk.css';
import '../../css/c/csj5nub5y.css';
import '../../css/l/lwjvcxb8q.css';
import '../../css/j/j0-ayccpo.css';
import '../../css/t/t5umg7rro.css';
import '../../css/l/le12kbbfh.css';
import '../../css/k/kcjf43bga.css';
import '../../css/t/ta2zb6pim.css';
import '../../css/k/k7l3dlb6u.css';
import '../../css/i/i05mbxqpc.css';
import '../../css/u/ubz-pkb7d.css';
import '../../css/y/y6e8xybbr.css';
import '../../css/a/azqwydbik.css';
import '../../css/u/u2j5pbbow.css';
import '../../css/i/i-izitchk.css';
import '../../css/p/p2217fbxb.css';
import '../../css/a/ajp1libbe.css';
import '../../css/x/x01w_lkhs.css';
import '../../css/o/ok87evbjc.css';
import '../../css/i/iyvni4xfp.css';
import '../../css/x/x99w6biww.css';
import '../../css/x/xsy1clpqu.css';
import '../../css/f/ft5mbbcqy.css';
import '../../css/x/x1esswb9j.css';
import '../../css/q/q9nxgx31s.css';
import '../../css/w/wz8exn-ad.css';
import '../../css/z/zrsw7hwyo.css';
import '../../css/u/uq6jb1nbc.css';
import '../../css/q/qf-2o8bln.css';
import '../../css/w/wdd_-0bmg.css';
import '../../css/s/snug8k1-b.css';
import '../../css/t/ttkvog02a.css';
import '../../css/p/p-x_g_b7m.css';
import '../../css/x/x6v8adwld.css';
import '../../css/d/dyyq5tb5e.css';
import '../../css/m/m3idmbcrh.css';
import '../../css/r/rk7gt_blu.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":301,"height":151};
const content = `<g class="bi12bsetm"><path class="tqs3vpmmc"/><path class="nxdg8xz_g"/><path class="v0kp6pbgp"/><path class="tyi647blx"/><path class="ti56t1b-y"/><path class="heq9_lbrw"/><circle class="ilvd6gbst"/><path class="ayqmttbwe"/><path class="w--ylccjk"/><path class="eclqd1smr"/><path class="f1ej4sbit"/><circle class="n61v_wt5g"/><path class="c62diobmw"/><path class="evq528j_k"/><path class="j657qptmb"/><path class="nbfk9ubyf"/><path class="uw8axu5xi"/><path class="ts4l8vbsa"/><path class="h5n7eurdv"/><path class="o7ep6_bnw"/><path class="m1r4_nb0f"/><path class="olt1ugbdv"/><path class="my8yrzb5a"/><circle transform="rotate(-104.406 52.685 11.038)" class="o1755xbbx"/><path class="iweh6ybyd"/><path class="bj8fdkb3d"/><path class="n01p3bb8p"/><path class="jjwv42bdh"/><path class="jb6q9ybou"/><path class="aoqwfravp"/><path class="jgrkhh1ha"/><path class="lm25pybxy"/><path class="mh911mq2u"/><path class="j012-xb-x"/><circle transform="rotate(-75.558 23.33 11.063)" class="vs7ba7bqx"/><path class="qt5hwrlbk"/><path class="csj5nub5y"/><path class="lwjvcxb8q"/><circle class="j0-ayccpo"/><circle class="t5umg7rro"/><circle class="le12kbbfh"/><circle class="kcjf43bga"/><circle class="ta2zb6pim"/><circle class="k7l3dlb6u"/><path class="i05mbxqpc"/><circle class="ubz-pkb7d"/><circle class="y6e8xybbr"/><circle class="azqwydbik"/><circle class="u2j5pbbow"/><circle class="i-izitchk"/><circle class="p2217fbxb"/><path class="ajp1libbe"/><path class="x01w_lkhs"/><path class="ok87evbjc"/><path class="iyvni4xfp"/><path class="x99w6biww"/><ellipse class="xsy1clpqu"/><path class="ft5mbbcqy"/><path class="x1esswb9j"/><circle class="q9nxgx31s"/><circle class="wz8exn-ad"/><circle class="zrsw7hwyo"/><circle class="uq6jb1nbc"/><circle class="qf-2o8bln"/><circle class="wdd_-0bmg"/><path class="snug8k1-b"/><ellipse class="ttkvog02a"/><path class="p-x_g_b7m"/><path class="x6v8adwld"/><path class="dyyq5tb5e"/><path class="m3idmbcrh"/><path class="rk7gt_blu"/></g>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="cif:om" /></template>
