<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/h/h15591b2u.css';
import '../../css/n/n0l9njbew.css';
import '../../css/u/up0e80b4z.css';
import '../../css/b/bhdqeqbzp.css';
import '../../css/o/ocydvbr2o.css';
import '../../css/x/xjcw_5h_z.css';
import '../../css/m/md54_ub3p.css';
import '../../css/v/vkc55xbqh.css';
import '../../css/m/mcapj9bdk.css';
import '../../css/h/hr8le_b-j.css';
import '../../css/t/tb9yswb_z.css';
import '../../css/r/rra6rlbpu.css';
import '../../css/a/aevcwxlgn.css';
import '../../css/u/uhyinqbok.css';
import '../../css/d/d7r0j8brk.css';
import '../../css/w/wwr3svh1u.css';
import '../../css/w/w8hbn_bhu.css';
import '../../css/b/bftvdgbda.css';
import '../../css/r/rx_cnrbur.css';
import '../../css/n/n9snjpmat.css';
import '../../css/y/yps54zb7y.css';
import '../../css/v/vfh0c2bct.css';
import '../../css/z/z-7qbxbaq.css';
import '../../css/h/hff454bzm.css';
import '../../css/w/wawqteb9i.css';
import '../../css/n/nemdwf8vn.css';
import '../../css/e/exab5cb_u.css';
import '../../css/r/r_qwsnb3b.css';
import '../../css/u/uurl1_q5d.css';
import '../../css/g/g6618eb7i.css';
import '../../css/t/tlmx48bqt.css';
import '../../css/w/w91gfjtyj.css';
import '../../css/a/actn4ub3q.css';
import '../../css/b/b2x5tkbsi.css';
import '../../css/p/pzkwhscgq.css';
import '../../css/g/gtr998bcu.css';
import '../../css/o/oj8f2h5ef.css';
import '../../css/k/kgsq9zbpl.css';
import '../../css/c/ctyn7abyn.css';
import '../../css/g/giik6t-mh.css';
import '../../css/m/mh-0fibjp.css';
import '../../css/r/r2g8pgoki.css';
import '../../css/r/r5cfs8bxy.css';
import '../../css/m/m0ev1tb4g.css';
import '../../css/f/famjz6bgd.css';
import '../../css/f/fr4sy4bhg.css';
import '../../css/r/rrdg703-f.css';
import '../../css/x/xkm1sbc2r.css';
import '../../css/e/e3v2opbaq.css';
import '../../css/k/kf-g21y1k.css';
import '../../css/t/tf9g334sx.css';
import '../../css/z/zc8x03v1c.css';
import '../../css/z/zcu5cdc7g.css';
import '../../css/y/y7diyhq8l.css';
import '../../css/w/we3jebbni.css';
import '../../css/o/opbzp3rpp.css';
import '../../css/e/ehe6ee9pe.css';
import '../../css/n/nrx4iacdq.css';
import '../../css/f/f0y2ou68z.css';
import '../../css/f/fzsnvxjdk.css';
import '../../css/d/du-9fubju.css';
import '../../css/c/c56sbyb1q.css';
import '../../css/i/ibb2d_b_o.css';
import '../../css/b/bbmvzfbvq.css';
import '../../css/n/n4c116r6r.css';
import '../../css/o/oco657bia.css';
import '../../css/i/io5i0dbem.css';
import '../../css/a/a_s7bcblv.css';
import '../../css/p/pt8959blw.css';
import '../../css/p/pipoz7bpj.css';
import '../../css/n/nf42j1b-n.css';
import '../../css/i/iuml5ubrz.css';
import '../../css/y/yfn3lub-y.css';
import '../../css/r/rbv-snbmz.css';
import '../../css/a/a_b9fombf.css';
import '../../css/v/vnq4pky3v.css';
import '../../css/u/u7wuu0b-p.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":128,"height":128};
const content = `<defs><filter id="SVG4GSC1bfN" color-interpolation-filters="sRGB"><feGaussianBlur result="blur" stdDeviation=".23"/><feComposite in="SourceGraphic" in2="blur" operator="atop" result="composite1"/><feComposite in2="composite1" operator="in" result="composite2"/><feComposite in2="composite2" operator="in" result="composite3"/></filter><filter id="SVGv8cpMbQa" color-interpolation-filters="sRGB"><feGaussianBlur result="blur" stdDeviation=".31"/><feComposite in="SourceGraphic" in2="blur" operator="atop" result="composite1"/><feComposite in2="composite1" operator="in" result="composite2"/><feComposite in2="composite2" operator="in" result="composite3"/></filter><filter id="SVG33Sy2dbX" color-interpolation-filters="sRGB"><feGaussianBlur result="blur" stdDeviation=".21"/><feComposite in="SourceGraphic" in2="blur" operator="atop" result="composite1"/><feComposite in2="composite1" operator="in" result="composite2"/><feComposite in2="composite2" operator="in" result="composite3"/></filter><filter id="SVGyu2qFhaV" color-interpolation-filters="sRGB"><feGaussianBlur result="blur" stdDeviation=".11"/><feComposite in="SourceGraphic" in2="blur" operator="atop" result="composite1"/><feComposite in2="composite1" operator="in" result="composite2"/><feComposite in2="composite2" operator="in" result="composite3"/></filter><filter id="SVGBMcljbde" color-interpolation-filters="sRGB"><feGaussianBlur result="blur" stdDeviation=".1"/><feComposite in="SourceGraphic" in2="blur" operator="atop" result="composite1"/><feComposite in2="composite1" operator="in" result="composite2"/><feComposite in2="composite2" operator="in" result="composite3"/></filter><filter id="SVGmrjMAd6c" width="1.03" height="1.117" x="-.015" y="-.059" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation=".186"/></filter><filter id="SVGFEO8NcdY" width="1.015" height="1.056" x="-.008" y="-.028" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation=".098"/></filter><filter id="SVGyEI5wb3J" width="1.028" height="1.191" x="-.014" y="-.095" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation=".163"/></filter><filter id="SVGeYDjCc0Y" width="1.119" height="1.099" x="-.059" y="-.05" color-interpolation-filters="sRGB"><feGaussianBlur result="blur" stdDeviation="1.084"/><feComposite in="SourceGraphic" in2="blur" operator="atop" result="composite1"/><feComposite in2="composite1" operator="in" result="composite2"/><feComposite in2="composite2" operator="in" result="composite3"/></filter><filter id="SVGLt0oH7zZ" width="1.053" height="1.044" x="-.026" y="-.022" color-interpolation-filters="sRGB"><feGaussianBlur result="fbSourceGraphic" stdDeviation=".424"/><feColorMatrix in="fbSourceGraphic" result="fbSourceGraphicAlpha" values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"/><feGaussianBlur in="fbSourceGraphic" result="blur" stdDeviation=".81"/><feComposite in="fbSourceGraphic" in2="blur" operator="atop" result="composite1"/><feComposite in2="composite1" operator="in" result="composite2"/><feComposite in2="composite2" operator="in" result="composite3"/></filter><linearGradient id="SVGhfWXzcgp" x1="97.988" x2="84.177" y1="119.56" y2="116.33" gradientUnits="userSpaceOnUse"><stop offset="0" class="h15591b2u"/><stop offset="1" class="n0l9njbew"/></linearGradient><linearGradient id="SVGUE1oGcqB" x1="48.706" x2="59.061" y1="81.451" y2="78.814" gradientUnits="userSpaceOnUse"><stop offset="0" class="up0e80b4z"/><stop offset="1" class="bhdqeqbzp"/></linearGradient><linearGradient id="SVGOqMq9ZAR" x1="49.354" x2="49.426" y1="75.243" y2="76.417" gradientUnits="userSpaceOnUse"><stop offset="0" class="ocydvbr2o"/><stop offset="1" class="xjcw_5h_z"/></linearGradient><linearGradient id="SVGMKVxdcxL" x1="38.639" x2="37.754" y1="75.171" y2="69.842" gradientUnits="userSpaceOnUse"><stop offset="0" class="md54_ub3p"/><stop offset="1" class="vkc55xbqh"/></linearGradient><linearGradient id="SVG4Mc2retk" x1="63.864" x2="64.746" y1="67.797" y2="69.831" gradientUnits="userSpaceOnUse"><stop offset="0" class="mcapj9bdk"/><stop offset="1" class="hr8le_b-j"/></linearGradient><linearGradient id="SVG7ATdFepz" x1="48.407" x2="49.492" y1="59.797" y2="58.712" gradientUnits="userSpaceOnUse"><stop offset="0" class="tb9yswb_z"/><stop offset="1" class="rra6rlbpu"/></linearGradient><linearGradient id="SVG9vTDhdxv" x1="48.136" x2="47.988" y1="70.034" y2="68.899" gradientUnits="userSpaceOnUse"><stop offset="0" class="aevcwxlgn"/><stop offset="1" class="uhyinqbok"/></linearGradient><linearGradient id="SVGA3E51dVp" x1="48.983" x2="49.186" y1="97.661" y2="97.22" gradientUnits="userSpaceOnUse"><stop offset="0" class="d7r0j8brk"/><stop offset="1" class="wwr3svh1u"/></linearGradient><linearGradient id="SVGoz1C2E3N" x1="66.313" x2="66.397" y1="59.868" y2="62.354" gradientUnits="userSpaceOnUse"><stop offset="0" class="w8hbn_bhu"/><stop offset="1" class="bftvdgbda"/></linearGradient><linearGradient id="SVGfboUbdWH" x1="47.186" x2="50.305" y1="37.017" y2="38.508" gradientUnits="userSpaceOnUse"><stop offset="0" class="rx_cnrbur"/><stop offset="1" class="n9snjpmat"/></linearGradient><linearGradient id="SVGWgHPv2yO" x1="45.831" x2="48.407" y1="83.119" y2="89.22" gradientUnits="userSpaceOnUse"><stop offset="0" class="yps54zb7y"/><stop offset="1" class="vfh0c2bct"/></linearGradient><radialGradient id="SVGo5dTLdsr" cx="55.64" cy="50.886" r="5.056" gradientTransform="rotate(-11.146 95.953 55.502)scale(1.03309 .846)" gradientUnits="userSpaceOnUse"><stop offset="0" class="z-7qbxbaq"/><stop offset="1" class="hff454bzm"/></radialGradient><radialGradient id="SVGxhHz0cit" cx="76.881" cy="50.965" r="3.778" gradientTransform="rotate(13.052 125.985 -26.51)scale(1.24496 1.18379)" gradientUnits="userSpaceOnUse"><stop offset="0" class="z-7qbxbaq"/><stop offset="1" class="hff454bzm"/></radialGradient><radialGradient id="SVGShswsb6a" cx="46.738" cy="46.196" r="24.536" gradientTransform="rotate(93.86 57.078 65.599)scale(.52956 1.2367)" gradientUnits="userSpaceOnUse"><stop offset="0" class="wawqteb9i"/><stop offset="1" class="nemdwf8vn"/></radialGradient><radialGradient id="SVGgyBMbnMA" cx="94.478" cy="30.526" r="32.374" gradientTransform="matrix(.10003 -.24267 .32605 .1344 52.096 48.694)" gradientUnits="userSpaceOnUse"><stop offset="0" class="exab5cb_u"/><stop offset="1" class="r_qwsnb3b"/></radialGradient><radialGradient id="SVGO9BdJc7l" cx="80.344" cy="98.345" r="23.782" gradientTransform="rotate(18.784 268.108 21.79)scale(1.40926 1.59886)" gradientUnits="userSpaceOnUse"><stop offset="0" class="h15591b2u"/><stop offset="1" class="md54_ub3p"/></radialGradient><radialGradient id="SVGEAJ2oboA" cx="79.278" cy="95.485" r="26.347" gradientTransform="rotate(25.94 124.321 109.32)scale(.98756 1.23302)" gradientUnits="userSpaceOnUse"><stop offset="0" class="h15591b2u"/><stop offset="1" class="uurl1_q5d"/></radialGradient></defs><path class="g6618eb7i"/><path class="tlmx48bqt"/><path class="w91gfjtyj"/><path filter="url(#SVGyu2qFhaV)" class="actn4ub3q"/><path class="b2x5tkbsi"/><path fill="url(#SVGShswsb6a)" class="pzkwhscgq"/><path class="gtr998bcu"/><path class="oj8f2h5ef"/><path class="kgsq9zbpl"/><path class="ctyn7abyn"/><path fill="url(#SVGWgHPv2yO)" class="giik6t-mh"/><path fill="url(#SVGfboUbdWH)" class="mh-0fibjp"/><path fill="url(#SVG7ATdFepz)" class="r2g8pgoki"/><path class="r5cfs8bxy"/><path filter="url(#SVGyu2qFhaV)" class="m0ev1tb4g"/><path filter="url(#SVGyu2qFhaV)" class="famjz6bgd"/><path class="fr4sy4bhg"/><path class="rrdg703-f"/><path fill="url(#SVGMKVxdcxL)" class="xkm1sbc2r"/><path fill="url(#SVG9vTDhdxv)" class="e3v2opbaq"/><path fill="url(#SVGOqMq9ZAR)" class="kf-g21y1k"/><path fill="url(#SVGUE1oGcqB)" filter="url(#SVG4GSC1bfN)" class="tf9g334sx"/><path filter="url(#SVGBMcljbde)" class="zc8x03v1c"/><path fill="url(#SVGA3E51dVp)" class="zcu5cdc7g"/><path class="y7diyhq8l"/><path fill="url(#SVGoz1C2E3N)" class="we3jebbni"/><path fill="url(#SVG4Mc2retk)" class="opbzp3rpp"/><path class="ehe6ee9pe"/><path filter="url(#SVGyu2qFhaV)" class="nrx4iacdq"/><path filter="url(#SVGv8cpMbQa)" class="f0y2ou68z"/><path class="fzsnvxjdk"/><path fill="url(#SVGhfWXzcgp)" class="du-9fubju"/><path filter="url(#SVG33Sy2dbX)" class="c56sbyb1q"/><path fill="url(#SVGgyBMbnMA)" class="ibb2d_b_o"/><path filter="url(#SVG33Sy2dbX)" class="bbmvzfbvq"/><path class="n4c116r6r"/><path fill="url(#SVGxhHz0cit)" class="oco657bia"/><path fill="url(#SVGo5dTLdsr)" class="io5i0dbem"/><path filter="url(#SVGyEI5wb3J)" class="a_s7bcblv"/><path filter="url(#SVGFEO8NcdY)" class="pt8959blw"/><path filter="url(#SVGmrjMAd6c)" class="pipoz7bpj"/><path class="nf42j1b-n"/><path class="iuml5ubrz"/><path class="yfn3lub-y"/><path fill="url(#SVGO9BdJc7l)" class="rbv-snbmz"/><path fill="url(#SVGEAJ2oboA)" filter="url(#SVGeYDjCc0Y)" class="a_b9fombf"/><path filter="url(#SVGLt0oH7zZ)" class="vnq4pky3v"/><path class="u7wuu0b-p"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="devicon:renpy" /></template>
