<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/f/ft5dv1b6b.css';
import '../../css/v/v_8uyccxu.css';
import '../../css/c/cso0v8b1w.css';
import '../../css/a/azj-1mvgf.css';
import '../../css/j/josde0tma.css';
import '../../css/e/ebdz8fniv.css';
import '../../css/v/vrwkyqbcy.css';
import '../../css/i/ifa0rwhbl.css';
import '../../css/j/jnzl_o9ol.css';
import '../../css/t/tsykrnbdz.css';
import '../../css/t/ts8c6kj3t.css';
import '../../css/d/dqo-37bez.css';
import '../../css/b/bg44wqbfn.css';
import '../../css/b/bl8ox72dm.css';
import '../../css/e/er-w0it4r.css';
import '../../css/v/vikaxdocm.css';
import '../../css/e/ezze244er.css';
import '../../css/b/bemco2cfy.css';
import '../../css/z/z121thyuy.css';
import '../../css/p/pdz4fxb9i.css';
import '../../css/i/iuhkpac3s.css';
import '../../css/l/lepzexr9r.css';
import '../../css/y/y86_nsbur.css';
import '../../css/x/xe6edm8bb.css';
import '../../css/a/av2vp2bld.css';
import '../../css/x/xn_dcwrwo.css';
import '../../css/u/u8g3_zafe.css';
import '../../css/a/allgbi0ue.css';
import '../../css/z/zn5wgpbpn.css';
import '../../css/p/pmk_gh_gt.css';
import '../../css/b/b6ijbwb4z.css';
import '../../css/e/e8cg5b1ye.css';
import '../../css/a/ab26pfbzy.css';
import '../../css/x/x6dgn7bqe.css';
import '../../css/c/chtkrsb_p.css';
import '../../css/b/bdmkhw0xl.css';
import '../../css/e/elq3yqn-m.css';
import '../../css/h/h8bryv4gp.css';
import '../../css/m/mbd6j_qbb.css';
import '../../css/q/quo0x3bck.css';
import '../../css/u/uk-vhdx9z.css';
import '../../css/o/oiujqibip.css';
import '../../css/k/k9kxfn-6t.css';
import '../../css/l/ly1876bvd.css';
import '../../css/u/uooc31xet.css';
import '../../css/w/w-xm3-bgq.css';
import '../../css/e/e1ekw1-mg.css';
import '../../css/k/ki6vmi9qz.css';
import '../../css/g/gzhrkubfb.css';
import '../../css/d/dj8a6jdxw.css';
import '../../css/t/tsuuox2ro.css';
import '../../css/b/b5glkqjtm.css';
import '../../css/a/a4vlcxoop.css';
import '../../css/l/l7s2jhrtd.css';
import '../../css/u/ubtfyfqmn.css';
import '../../css/v/v_n1-ob6b.css';
import '../../css/g/gvx6ltb6v.css';
import '../../css/q/qduw14b9u.css';
import '../../css/z/zejr6kbxy.css';
import '../../css/o/ow_9wsbvv.css';
import '../../css/d/d0yv8fbos.css';
import '../../css/t/tqa5hnbjx.css';
import '../../css/v/vc--wpv5i.css';
import '../../css/w/w6h37rn-x.css';
import '../../css/n/nw6sdtbqp.css';
import '../../css/g/g4hf30blt.css';
import '../../css/g/gol5nb4lr.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":2500,"height":2345};
const content = `<g class="ft5dv1b6b"><g clip-path="url(#SVG8pBxJd8l)"><path class="v_8uyccxu"/><path class="cso0v8b1w"/><path fill="url(#SVGmQIJAcAz)" class="azj-1mvgf"/><path class="josde0tma"/><path class="ebdz8fniv"/><path fill="url(#SVGHYOLcceZ)" class="vrwkyqbcy"/><path fill="url(#SVG2kOIDeoh)" class="ifa0rwhbl"/><path fill="url(#SVG6j3CAc3D)" class="jnzl_o9ol"/><path fill="url(#SVGrpvEwe4j)" class="tsykrnbdz"/><path fill="url(#SVGywqf6Gvb)" class="ts8c6kj3t"/><path fill="url(#SVGwFqULbQL)" class="dqo-37bez"/><path fill="url(#SVGWxntXcwD)" class="bg44wqbfn"/><path fill="url(#SVGIZpHcvqb)" class="bl8ox72dm"/><path fill="url(#SVGKNKIqdEC)" class="er-w0it4r"/><path class="vikaxdocm"/><path class="ezze244er"/><path fill="url(#SVGz6dwEd6z)" class="bemco2cfy"/><path fill="url(#SVGrAhyEbHI)" class="z121thyuy"/><path fill="url(#SVGgEjgLbQK)" class="pdz4fxb9i"/><path fill="url(#SVGGBXHwefK)" class="iuhkpac3s"/><path fill="url(#SVGMYAg7d8l)" class="lepzexr9r"/><path fill="url(#SVG2yT6betC)" class="y86_nsbur"/><path fill="url(#SVG6E6IHdJD)" class="xe6edm8bb"/><path fill="url(#SVG3Ayjggwp)" class="av2vp2bld"/><path fill="url(#SVGOciueemu)" class="xn_dcwrwo"/><path fill="url(#SVGh1Oo7eRe)" class="u8g3_zafe"/><path class="allgbi0ue"/><path fill="url(#SVGkBYauf5I)" class="zn5wgpbpn"/><path class="pmk_gh_gt"/><path fill="url(#SVGYwThVcNR)" class="b6ijbwb4z"/><path fill="url(#SVGH6kR3b2r)" class="e8cg5b1ye"/><path fill="url(#SVGiCVFgeCu)" class="ab26pfbzy"/><path class="x6dgn7bqe"/><path class="chtkrsb_p"/><path class="bdmkhw0xl"/><path class="elq3yqn-m"/><path class="h8bryv4gp"/><path class="mbd6j_qbb"/><path class="quo0x3bck"/><path class="uk-vhdx9z"/><path class="oiujqibip"/></g><defs><linearGradient id="SVGmQIJAcAz" x1="887.4" x2="1426.2" y1="1515.4" y2="2354.9" gradientUnits="userSpaceOnUse"><stop class="k9kxfn-6t"/><stop offset=".7" class="k9kxfn-6t"/><stop offset="1" class="ly1876bvd"/></linearGradient><linearGradient id="SVGHYOLcceZ" x1="619.7" x2="570.9" y1="1842.9" y2="2039.3" gradientUnits="userSpaceOnUse"><stop class="uooc31xet"/><stop offset=".3" class="uooc31xet"/><stop offset="1" class="w-xm3-bgq"/></linearGradient><linearGradient id="SVG2kOIDeoh" x1="697.5" x2="637.8" y1="1937.2" y2="2170.3" gradientUnits="userSpaceOnUse"><stop class="uooc31xet"/><stop offset=".3" class="uooc31xet"/><stop offset="1" class="w-xm3-bgq"/></linearGradient><linearGradient id="SVG6j3CAc3D" x1="860.8" x2="767.6" y1="2032" y2="2378.4" gradientUnits="userSpaceOnUse"><stop class="uooc31xet"/><stop offset=".3" class="uooc31xet"/><stop offset="1" class="w-xm3-bgq"/></linearGradient><linearGradient id="SVGrpvEwe4j" x1="1837" x2="1891.9" y1="2168.8" y2="2355.9" gradientUnits="userSpaceOnUse"><stop class="e1ekw1-mg"/><stop offset=".4" class="uooc31xet"/><stop offset="1" class="ki6vmi9qz"/></linearGradient><linearGradient id="SVGywqf6Gvb" x1="1929.1" x2="2011.7" y1="2064.7" y2="2237.2" gradientUnits="userSpaceOnUse"><stop class="e1ekw1-mg"/><stop offset=".4" class="uooc31xet"/><stop offset="1" class="ki6vmi9qz"/></linearGradient><linearGradient id="SVGwFqULbQL" x1="2003.9" x2="2071.1" y1="1992.4" y2="2115.3" gradientUnits="userSpaceOnUse"><stop class="e1ekw1-mg"/><stop offset=".4" class="uooc31xet"/><stop offset="1" class="ki6vmi9qz"/></linearGradient><linearGradient id="SVGWxntXcwD" x1="1575.7" x2="1575.7" y1="453.7" y2="1070" gradientUnits="userSpaceOnUse"><stop class="gzhrkubfb"/><stop offset=".4" class="gzhrkubfb"/><stop offset=".7" class="dj8a6jdxw"/><stop offset="1" class="dj8a6jdxw"/></linearGradient><linearGradient id="SVGIZpHcvqb" x1="1707.5" x2="1992.3" y1="1011.2" y2="1479.7" gradientUnits="userSpaceOnUse"><stop class="tsuuox2ro"/><stop offset=".5" class="tsuuox2ro"/><stop offset="1" class="b5glkqjtm"/></linearGradient><linearGradient id="SVGKNKIqdEC" x1="1264" x2="1550.6" y1="947.5" y2="1427.7" gradientUnits="userSpaceOnUse"><stop class="tsuuox2ro"/><stop offset=".5" class="tsuuox2ro"/><stop offset="1" class="b5glkqjtm"/></linearGradient><linearGradient id="SVGz6dwEd6z" x1="1945.7" x2="1977.7" y1="1986.8" y2="2011.6" gradientUnits="userSpaceOnUse"><stop class="a4vlcxoop"/><stop offset="1" class="l7s2jhrtd"/></linearGradient><linearGradient id="SVGrAhyEbHI" x1="1867.1" x2="1906.2" y1="2077.2" y2="2128.2" gradientUnits="userSpaceOnUse"><stop class="a4vlcxoop"/><stop offset="1" class="l7s2jhrtd"/></linearGradient><linearGradient id="SVGgEjgLbQK" x1="1126.5" x2="970.9" y1="2143.3" y2="2406.2" gradientUnits="userSpaceOnUse"><stop class="ubtfyfqmn"/><stop offset="1" class="v_n1-ob6b"/></linearGradient><linearGradient id="SVGGBXHwefK" x1="1737.3" x2="1777.2" y1="2177" y2="2265.9" gradientUnits="userSpaceOnUse"><stop class="a4vlcxoop"/><stop offset="1" class="l7s2jhrtd"/></linearGradient><linearGradient id="SVGMYAg7d8l" x1="868.7" x2="755.2" y1="2003.4" y2="2204.6" gradientUnits="userSpaceOnUse"><stop class="ubtfyfqmn"/><stop offset="1" class="v_n1-ob6b"/></linearGradient><linearGradient id="SVG2yT6betC" x1="757.6" x2="663.9" y1="1894.8" y2="2066" gradientUnits="userSpaceOnUse"><stop class="ubtfyfqmn"/><stop offset="1" class="v_n1-ob6b"/></linearGradient><linearGradient id="SVG6E6IHdJD" x1="2394.3" x2="2004.9" y1="1310.1" y2="1704.8" gradientUnits="userSpaceOnUse"><stop class="gvx6ltb6v"/><stop offset=".1" class="gvx6ltb6v"/><stop offset=".4" class="k9kxfn-6t"/><stop offset="1" class="k9kxfn-6t"/></linearGradient><linearGradient id="SVG3Ayjggwp" x1="2354" x2="1867.7" y1="1206.8" y2="1730.7" gradientUnits="userSpaceOnUse"><stop class="qduw14b9u"/><stop offset=".3" class="zejr6kbxy"/><stop offset=".7" class="ow_9wsbvv"/><stop offset="1" class="d0yv8fbos"/></linearGradient><linearGradient id="SVGOciueemu" x1="2105.3" x2="2105.3" y1="1381.3" y2="1453.1" gradientUnits="userSpaceOnUse"><stop class="tqa5hnbjx"/><stop offset="1" class="vc--wpv5i"/></linearGradient><linearGradient id="SVGh1Oo7eRe" x1="2274.5" x2="2274.5" y1="1272.6" y2="1456.3" gradientUnits="userSpaceOnUse"><stop class="tqa5hnbjx"/><stop offset="1" class="vc--wpv5i"/></linearGradient><linearGradient id="SVGkBYauf5I" x1="288.4" x2="624.3" y1="689.3" y2="1846.7" gradientUnits="userSpaceOnUse"><stop class="gvx6ltb6v"/><stop offset=".2" class="gvx6ltb6v"/><stop offset=".7" class="k9kxfn-6t"/><stop offset="1" class="k9kxfn-6t"/></linearGradient><linearGradient id="SVGYwThVcNR" x1="11.7" x2="616.7" y1="1035.8" y2="1632" gradientUnits="userSpaceOnUse"><stop class="gvx6ltb6v"/><stop offset=".3" class="w6h37rn-x"/><stop offset=".5" class="nw6sdtbqp"/><stop offset="1" class="d0yv8fbos"/></linearGradient><linearGradient id="SVGH6kR3b2r" x1="578.3" x2="585.4" y1="1143.8" y2="1348.2" gradientUnits="userSpaceOnUse"><stop class="tqa5hnbjx"/><stop offset="1" class="vc--wpv5i"/></linearGradient><linearGradient id="SVGiCVFgeCu" x1="367.8" x2="381.3" y1="852.8" y2="1240.2" gradientUnits="userSpaceOnUse"><stop class="g4hf30blt"/><stop offset="1" class="vc--wpv5i"/></linearGradient><clipPath id="SVG8pBxJd8l"><path class="gol5nb4lr"/></clipPath></defs></g>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="thesvg-color:rsbuild" /></template>
