<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/f/ft5dv1b6b.css';
import '../../css/u/uuazlv-wm.css';
import '../../css/d/d2kvgvbvc.css';
import '../../css/n/n4p2epb_c.css';
import '../../css/q/qj46ug8gh.css';
import '../../css/t/tup7klbhr.css';
import '../../css/u/uw4p60psh.css';
import '../../css/t/t13xdnb5s.css';
import '../../css/j/jnbs5iqfg.css';
import '../../css/h/h7s_6qbor.css';
import '../../css/z/zw1ytxytb.css';
import '../../css/m/mmlst8cjn.css';
import '../../css/f/fcrwwib9s.css';
import '../../css/u/uiimdoywa.css';
import '../../css/l/l2iw09bjh.css';
import '../../css/z/zp5lyr7yq.css';
import '../../css/w/w5y3wmb0u.css';
import '../../css/d/dd8epksnm.css';
import '../../css/o/o1wyybddv.css';
import '../../css/q/qs6kaik-l.css';
import '../../css/n/ncbjkcyhj.css';
import '../../css/j/j1y0librw.css';
import '../../css/j/jl8pcyvuf.css';
import '../../css/a/anp5c3pdg.css';
import '../../css/h/h8fnprbnu.css';
import '../../css/q/q7xz9abfp.css';
import '../../css/v/vc--wpv5i.css';
import '../../css/w/wr97chdyu.css';
import '../../css/o/oyjo3ex1c.css';
import '../../css/w/wxf-xc86f.css';
import '../../css/q/q9tep7byl.css';
import '../../css/v/vgglilblh.css';
import '../../css/e/ezidwnbja.css';
import '../../css/d/dpr9tb3ch.css';
import '../../css/l/lsv7azf7j.css';
import '../../css/w/w_afh7bgq.css';
import '../../css/i/i_f-8ebbv.css';
import '../../css/w/w8ttm0bgd.css';
import '../../css/q/qw5y8xbnh.css';
import '../../css/s/s8aw0sl5f.css';
import '../../css/u/ug4qrab9a.css';
import '../../css/g/gk6kz_ald.css';
import '../../css/y/yjb2dqbqe.css';
import '../../css/d/ddk317bha.css';
import '../../css/f/f4ld04byb.css';
import '../../css/s/six_5zb0y.css';
import '../../css/c/cqcs1lp7p.css';
import '../../css/u/u0l4xx4ah.css';
import '../../css/o/oe74w3r0p.css';
import '../../css/v/veuf6qxqw.css';
import '../../css/h/h3xd-3bzt.css';
import '../../css/v/v4700dkua.css';
import '../../css/i/iipf5j-mn.css';
import '../../css/d/dtgi8tbtl.css';
import '../../css/k/kv77ch53o.css';
import '../../css/q/q91zgcc_y.css';
import '../../css/l/l9c3zxbog.css';
import '../../css/w/wqwfuj05f.css';
import '../../css/m/m0lf0xtnz.css';
import '../../css/d/d1bgm_xyy.css';
import '../../css/r/r70gc76fy.css';
import '../../css/y/y3ybutbxv.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":256,"height":256};
const content = `<g class="ft5dv1b6b"><rect class="uuazlv-wm"/><g clip-path="url(#SVGanFeIbkr)" clip-rule="evenodd" class="d2kvgvbvc"><path fill="url(#SVGysfDGcIy)" class="n4p2epb_c"/><path fill="url(#SVGmWXJBbOA)" class="qj46ug8gh"/><path fill="url(#SVGk887rbsV)" class="tup7klbhr"/><path fill="url(#SVGJEZweXBC)" class="uw4p60psh"/><path fill="url(#SVGW7xXpc0k)" class="t13xdnb5s"/><path fill="url(#SVGlq2nEeuk)" class="jnbs5iqfg"/><path fill="url(#SVG5evk4cLJ)" class="h7s_6qbor"/><path fill="url(#SVGkIFOzbgb)" class="zw1ytxytb"/><path class="mmlst8cjn"/><path fill="url(#SVGYD4Oh66t)" class="fcrwwib9s"/><path fill="url(#SVGjZrz7bTR)" class="uiimdoywa"/><path fill="url(#SVGPd9cNcHs)" class="l2iw09bjh"/><path fill="url(#SVG1iQ4levs)" class="zp5lyr7yq"/><path class="w5y3wmb0u"/><path fill="url(#SVGXvSIIb5v)" class="dd8epksnm"/><path fill="url(#SVGEfMMYdSG)" class="o1wyybddv"/><path fill="url(#SVGLb8IfeSM)" class="qs6kaik-l"/><path fill="url(#SVGTNbH0cxp)" class="ncbjkcyhj"/></g><defs><linearGradient id="SVGysfDGcIy" x1="196.145" x2="158.172" y1="233.825" y2="166.782" gradientUnits="userSpaceOnUse"><stop class="j1y0librw"/><stop offset=".41" class="jl8pcyvuf"/><stop offset=".99" class="anp5c3pdg"/><stop offset="1" class="anp5c3pdg"/></linearGradient><linearGradient id="SVGmWXJBbOA" x1="215.061" x2="166.123" y1="177.506" y2="144.666" gradientUnits="userSpaceOnUse"><stop class="h8fnprbnu"/><stop offset=".99" class="q7xz9abfp"/><stop offset="1" class="q7xz9abfp"/></linearGradient><linearGradient id="SVGk887rbsV" x1="175.905" x2="126.969" y1="235.857" y2="203.017" gradientUnits="userSpaceOnUse"><stop class="h8fnprbnu"/><stop offset=".99" class="q7xz9abfp"/><stop offset="1" class="q7xz9abfp"/></linearGradient><linearGradient id="SVGJEZweXBC" x1="73.155" x2="80.742" y1="153.734" y2="203.038" gradientUnits="userSpaceOnUse"><stop class="vc--wpv5i"/><stop offset=".23" class="wr97chdyu"/><stop offset=".46" class="oyjo3ex1c"/><stop offset=".99" class="wxf-xc86f"/><stop offset="1" class="wxf-xc86f"/></linearGradient><linearGradient id="SVGW7xXpc0k" x1="125.336" x2="128.131" y1="107.695" y2="158.014" gradientUnits="userSpaceOnUse"><stop class="vc--wpv5i"/><stop offset=".23" class="q9tep7byl"/><stop offset=".56" class="vgglilblh"/><stop offset=".99" class="ezidwnbja"/><stop offset="1" class="ezidwnbja"/></linearGradient><linearGradient id="SVGlq2nEeuk" x1="171.642" x2="180.01" y1="61.186" y2="97.249" gradientUnits="userSpaceOnUse"><stop class="vc--wpv5i"/><stop offset=".18" class="dpr9tb3ch"/><stop offset=".4" class="lsv7azf7j"/><stop offset=".99" class="ezidwnbja"/><stop offset="1" class="ezidwnbja"/></linearGradient><linearGradient id="SVG5evk4cLJ" x1="146.089" x2="182.15" y1="48.485" y2="30.455" gradientUnits="userSpaceOnUse"><stop class="vc--wpv5i"/><stop offset=".54" class="w_afh7bgq"/><stop offset=".99" class="i_f-8ebbv"/><stop offset="1" class="i_f-8ebbv"/></linearGradient><linearGradient id="SVGkIFOzbgb" x1="41.546" x2="44.514" y1="141.164" y2="170.879" gradientUnits="userSpaceOnUse"><stop class="vc--wpv5i"/><stop offset=".31" class="w8ttm0bgd"/><stop offset=".99" class="qw5y8xbnh"/><stop offset="1" class="qw5y8xbnh"/></linearGradient><linearGradient id="SVGYD4Oh66t" x1="21.142" x2="160.661" y1="178.912" y2="35.448" gradientUnits="userSpaceOnUse"><stop class="s8aw0sl5f"/><stop offset=".07" class="vc--wpv5i"/><stop offset=".17" class="vc--wpv5i"/><stop offset=".27" class="ug4qrab9a"/><stop offset=".33" class="gk6kz_ald"/><stop offset=".46" class="yjb2dqbqe"/><stop offset=".72" class="ddk317bha"/><stop offset=".99" class="f4ld04byb"/><stop offset="1" class="f4ld04byb"/></linearGradient><linearGradient id="SVGjZrz7bTR" x1="128.009" x2="85.985" y1="193.383" y2="183.011" gradientUnits="userSpaceOnUse"><stop class="six_5zb0y"/><stop offset=".54" class="cqcs1lp7p"/><stop offset=".99" class="u0l4xx4ah"/><stop offset="1" class="u0l4xx4ah"/></linearGradient><linearGradient id="SVGPd9cNcHs" x1="200.19" x2="162.857" y1="142.944" y2="109.484" gradientUnits="userSpaceOnUse"><stop class="oe74w3r0p"/><stop offset=".99" class="veuf6qxqw"/><stop offset="1" class="veuf6qxqw"/></linearGradient><linearGradient id="SVG1iQ4levs" x1="213.906" x2="195.31" y1="81.55" y2="61.67" gradientUnits="userSpaceOnUse"><stop class="h3xd-3bzt"/><stop offset=".99" class="v4700dkua"/><stop offset="1" class="v4700dkua"/></linearGradient><linearGradient id="SVGLb8IfeSM" x1="62.229" x2="47.075" y1="217.279" y2="165.863" gradientUnits="userSpaceOnUse"><stop class="iipf5j-mn"/><stop offset=".43" class="dtgi8tbtl"/><stop offset=".99" class="kv77ch53o"/><stop offset="1" class="kv77ch53o"/></linearGradient><linearGradient id="SVGTNbH0cxp" x1="178.491" x2="212.466" y1="46.901" y2="61.899" gradientUnits="userSpaceOnUse"><stop class="q91zgcc_y"/><stop offset=".44" class="l9c3zxbog"/><stop offset=".99" class="wqwfuj05f"/><stop offset="1" class="wqwfuj05f"/></linearGradient><radialGradient id="SVGXvSIIb5v" cx="0" cy="0" r="1" gradientTransform="translate(168.67 110.124)scale(45.7496)" gradientUnits="userSpaceOnUse"><stop class="ezidwnbja"/><stop offset=".99" class="m0lf0xtnz"/><stop offset="1" class="m0lf0xtnz"/></radialGradient><radialGradient id="SVGEfMMYdSG" cx="0" cy="0" r="1" gradientTransform="translate(105.313 170.414)scale(60.818)" gradientUnits="userSpaceOnUse"><stop class="d1bgm_xyy"/><stop offset=".99" class="r70gc76fy"/><stop offset="1" class="r70gc76fy"/></radialGradient><clipPath id="SVGanFeIbkr"><path class="y3ybutbxv"/></clipPath></defs></g>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="skill-icons:ruby" /></template>
