<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/b/bi12bsetm.css';
import '../../css/z/zyexufb0a.css';
import '../../css/z/zq64wzaxk.css';
import '../../css/w/wq_se57hl.css';
import '../../css/q/q7ohec5rs.css';
import '../../css/t/t4hxotsdn.css';
import '../../css/q/qco9dpkxb.css';
import '../../css/e/e9p7_m0gz.css';
import '../../css/m/m5z4qf9xz.css';
import '../../css/l/lxpqyabxn.css';
import '../../css/t/t3zfugboo.css';
import '../../css/i/iyt6bym1g.css';
import '../../css/h/hjj87n_2c.css';
import '../../css/f/fas_rpvpq.css';
import '../../css/j/jr11lobfc.css';
import '../../css/p/pl51_7szh.css';
import '../../css/i/ibedewypt.css';
import '../../css/d/dh0_yefgj.css';
import '../../css/n/nairf7bct.css';
import '../../css/v/vedimybpg.css';
import '../../css/h/hcugrvaxp.css';
import '../../css/j/jut9ctx_c.css';
import '../../css/b/bf7266bbi.css';
import '../../css/u/ut_bpu90f.css';
import '../../css/d/dmjl5sbhy.css';
import '../../css/j/jqe1v3j3p.css';
import '../../css/r/rteonse5v.css';
import '../../css/r/rh5krzgmh.css';
import '../../css/z/zbkoicc7u.css';
import '../../css/j/j5c2e8bfp.css';
import '../../css/i/i-rkv9bkt.css';
import '../../css/v/va06wrbry.css';
import '../../css/n/n8be5gldz.css';
import '../../css/h/h7rfjlbkn.css';
import '../../css/d/dbmahvb5h.css';
import '../../css/t/tls9-81-n.css';
import '../../css/m/mwh32wysl.css';
import '../../css/u/uk-g3fbcz.css';
import '../../css/o/ofx_4rqei.css';
import '../../css/x/xnyaqjcli.css';
import '../../css/o/ohtfabbqu.css';
import '../../css/b/byj6grbeu.css';
import '../../css/x/xv1z1gbnw.css';
import '../../css/l/lpqi_vfgp.css';
import '../../css/r/rp12115xl.css';
import '../../css/r/rc0d9x46d.css';
import '../../css/o/o40hv5fsj.css';
import '../../css/c/csqbx8fos.css';
import '../../css/y/yj5u_5b6c.css';
import '../../css/n/nzildcb7u.css';
import '../../css/z/zs2gw0adt.css';
import '../../css/x/xgblvwbtu.css';
import '../../css/x/xxor27add.css';
import '../../css/i/i3mih_3zj.css';
import '../../css/j/jxb-1ybxs.css';
import '../../css/x/xd6drtl0z.css';
import '../../css/f/ful2ccbyl.css';
import '../../css/u/ul8bitbro.css';
import '../../css/u/u3oe5zbio.css';
import '../../css/s/snikis8ce.css';
import '../../css/v/vpp0mob8n.css';
import '../../css/d/dwt3t1eue.css';
import '../../css/x/xu988zbhq.css';
import '../../css/c/c4b3pabft.css';
import '../../css/o/ok4k49bnt.css';
import '../../css/g/gqfocpb7h.css';
import '../../css/v/vm56hdbbc.css';
import '../../css/q/qps50cq_d.css';
import '../../css/h/h7g0tpb1h.css';
import '../../css/z/z026i1bjj.css';
import '../../css/z/z0sbi-nrs.css';
import '../../css/q/qsn-vpbku.css';
import '../../css/w/ww9-r5b0f.css';
import '../../css/d/dta4rac_g.css';
import '../../css/q/q928q4o9k.css';
import '../../css/u/uyfek97jc.css';
import '../../css/q/qgluwn_yj.css';
import '../../css/v/vvgkgj7nx.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":301,"height":201};
const content = `<g class="bi12bsetm"><path class="zyexufb0a"/><path class="zq64wzaxk"/><path class="wq_se57hl"/><path class="q7ohec5rs"/><path class="t4hxotsdn"/><path class="qco9dpkxb"/><path class="e9p7_m0gz"/><path class="m5z4qf9xz"/><path class="lxpqyabxn"/><path class="t3zfugboo"/><path class="iyt6bym1g"/><path class="hjj87n_2c"/><path class="fas_rpvpq"/><path class="jr11lobfc"/><path class="pl51_7szh"/><path class="ibedewypt"/><path class="dh0_yefgj"/><path class="nairf7bct"/><path class="vedimybpg"/><path class="hcugrvaxp"/><path class="jut9ctx_c"/><path class="bf7266bbi"/><path class="ut_bpu90f"/><path class="dmjl5sbhy"/><path class="jqe1v3j3p"/><path class="rteonse5v"/><path class="rh5krzgmh"/><path class="zbkoicc7u"/><path class="j5c2e8bfp"/><path class="i-rkv9bkt"/><path class="va06wrbry"/><path class="n8be5gldz"/><path class="h7rfjlbkn"/><path class="dbmahvb5h"/><path class="tls9-81-n"/><path class="mwh32wysl"/><path class="uk-g3fbcz"/><path class="ofx_4rqei"/><path class="xnyaqjcli"/><path class="ohtfabbqu"/><path class="byj6grbeu"/><path class="xv1z1gbnw"/><path class="lpqi_vfgp"/><path class="rp12115xl"/><path class="rc0d9x46d"/><path class="o40hv5fsj"/><path class="csqbx8fos"/><path class="yj5u_5b6c"/><path class="nzildcb7u"/><path class="zs2gw0adt"/><path class="xgblvwbtu"/><path class="xxor27add"/><path class="i3mih_3zj"/><path class="jxb-1ybxs"/><path class="xd6drtl0z"/><path class="ful2ccbyl"/><path class="ul8bitbro"/><path class="u3oe5zbio"/><path class="snikis8ce"/><path class="vpp0mob8n"/><path class="dwt3t1eue"/><path class="xu988zbhq"/><path class="c4b3pabft"/><path class="ok4k49bnt"/><path class="gqfocpb7h"/><path class="vm56hdbbc"/><path class="qps50cq_d"/><path class="h7g0tpb1h"/><path class="z026i1bjj"/><path class="z0sbi-nrs"/><path class="qsn-vpbku"/><path class="ww9-r5b0f"/><path class="dta4rac_g"/><path class="q928q4o9k"/><path class="uyfek97jc"/><path class="qgluwn_yj"/><path class="vvgkgj7nx"/></g>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="cif:bt" /></template>
