<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/r/rqjbujbsp.css';
import '../../css/q/qgnp5cb4r.css';
import '../../css/o/oc6dybb2z.css';
import '../../css/p/p7i62-78n.css';
import '../../css/v/vg8uzsbwa.css';
import '../../css/x/xgq0jdbhd.css';
import '../../css/g/g69d_nr1e.css';
import '../../css/l/lwlpgrwtk.css';
import '../../css/c/c9phsobye.css';
import '../../css/m/m97bqnbfn.css';
import '../../css/k/k_t9d4_st.css';
import '../../css/v/vf42t_jzt.css';
import '../../css/t/tjen39bmd.css';
import '../../css/o/om74372sc.css';
import '../../css/x/xxt_u1v2c.css';
import '../../css/r/rn4r82bfv.css';
import '../../css/h/hpuu0fjkz.css';
import '../../css/l/l-pxvfjlb.css';
import '../../css/d/dgodczr8q.css';
import '../../css/y/yt8se8nvp.css';
import '../../css/q/qa7y2xbel.css';
import '../../css/q/qidc3g6bb.css';
import '../../css/q/q0x40klox.css';
import '../../css/y/y56q-_xtz.css';
import '../../css/b/bnehyjtet.css';
import '../../css/c/c_nptzxdf.css';
import '../../css/f/fspf2cc8a.css';
import '../../css/z/zlm3ccb8x.css';
import '../../css/r/r9xhlokyl.css';
import '../../css/e/e-cc1bzdo.css';
import '../../css/n/n285smbqc.css';
import '../../css/s/sedxi245y.css';
import '../../css/g/g-a2uqe-h.css';
import '../../css/d/dkknsfbkd.css';
import '../../css/l/lqq952h4f.css';
import '../../css/j/juqt_zp2c.css';
import '../../css/i/izd11fxjd.css';
import '../../css/x/xtoxfa4zw.css';
import '../../css/z/zr87a77rm.css';
import '../../css/q/q59l84bvf.css';
import '../../css/u/unl3x5biv.css';
import '../../css/d/dnd41wbik.css';
import '../../css/l/lk7ug0bpj.css';
import '../../css/p/pzbi_5btp.css';
import '../../css/x/x3432c4wn.css';
import '../../css/t/t8od7x0yi.css';
import '../../css/k/k26nxtb8z.css';
import '../../css/e/ehfhqhbzh.css';
import '../../css/r/rwv3vybdu.css';
import '../../css/t/t43n2bbii.css';
import '../../css/f/fu5gzzbsr.css';
import '../../css/h/hygc9gflx.css';
import '../../css/g/gvkjly-0x.css';
import '../../css/t/t-sl1ccbz.css';
import '../../css/r/rwsuabj6s.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":48,"height":48};
const content = `<path class="rqjbujbsp"/><path class="qgnp5cb4r"/><path class="oc6dybb2z"/><path class="p7i62-78n"/><path class="vg8uzsbwa"/><path class="xgq0jdbhd"/><path class="g69d_nr1e"/><path class="lwlpgrwtk"/><path class="c9phsobye"/><path class="m97bqnbfn"/><path class="k_t9d4_st"/><path class="vf42t_jzt"/><path class="tjen39bmd"/><path class="om74372sc"/><path class="xxt_u1v2c"/><path class="rn4r82bfv"/><path class="hpuu0fjkz"/><path class="l-pxvfjlb"/><path class="dgodczr8q"/><path class="yt8se8nvp"/><path class="qa7y2xbel"/><path class="qidc3g6bb"/><path class="q0x40klox"/><path class="y56q-_xtz"/><path class="bnehyjtet"/><path class="c_nptzxdf"/><path class="fspf2cc8a"/><path class="zlm3ccb8x"/><path class="r9xhlokyl"/><path class="e-cc1bzdo"/><path class="n285smbqc"/><path class="sedxi245y"/><path class="g-a2uqe-h"/><path class="dkknsfbkd"/><path class="lqq952h4f"/><path class="juqt_zp2c"/><path class="izd11fxjd"/><path class="xtoxfa4zw"/><path class="zr87a77rm"/><path class="q59l84bvf"/><path class="unl3x5biv"/><path class="dnd41wbik"/><path class="lk7ug0bpj"/><path class="pzbi_5btp"/><path class="x3432c4wn"/><path class="t8od7x0yi"/><path class="k26nxtb8z"/><path class="ehfhqhbzh"/><path class="rwv3vybdu"/><path class="t43n2bbii"/><path class="fu5gzzbsr"/><path class="hygc9gflx"/><path class="gvkjly-0x"/><path class="t-sl1ccbz"/><path class="rwsuabj6s"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="streamline-emojis:family-man-man-boy-boy-2" /></template>
