<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/r/rqjbujbsp.css';
import '../../css/q/qgnp5cb4r.css';
import '../../css/o/oc6dybb2z.css';
import '../../css/p/p7i62-78n.css';
import '../../css/v/vg8uzsbwa.css';
import '../../css/x/xgq0jdbhd.css';
import '../../css/g/g69d_nr1e.css';
import '../../css/l/lwlpgrwtk.css';
import '../../css/c/c9phsobye.css';
import '../../css/m/m97bqnbfn.css';
import '../../css/k/k_t9d4_st.css';
import '../../css/v/vf42t_jzt.css';
import '../../css/t/tjen39bmd.css';
import '../../css/o/om74372sc.css';
import '../../css/x/xxt_u1v2c.css';
import '../../css/r/rn4r82bfv.css';
import '../../css/h/hpuu0fjkz.css';
import '../../css/l/l-pxvfjlb.css';
import '../../css/d/dgodczr8q.css';
import '../../css/y/yt8se8nvp.css';
import '../../css/q/qa7y2xbel.css';
import '../../css/q/qidc3g6bb.css';
import '../../css/g/gjs9uqbtg.css';
import '../../css/y/y56q-_xtz.css';
import '../../css/b/bnehyjtet.css';
import '../../css/c/c_nptzxdf.css';
import '../../css/f/fspf2cc8a.css';
import '../../css/z/zlm3ccb8x.css';
import '../../css/r/r9xhlokyl.css';
import '../../css/e/e-cc1bzdo.css';
import '../../css/f/fil80-1iq.css';
import '../../css/q/qrj6mpbxq.css';
import '../../css/z/zf-1i_aza.css';
import '../../css/t/tgy2kc8wp.css';
import '../../css/z/zvocteb3b.css';
import '../../css/g/g-a2uqe-h.css';
import '../../css/d/dkknsfbkd.css';
import '../../css/l/lqq952h4f.css';
import '../../css/j/juqt_zp2c.css';
import '../../css/f/fvg2_4frg.css';
import '../../css/u/unl3x5biv.css';
import '../../css/d/dnd41wbik.css';
import '../../css/n/naa-_fz9o.css';
import '../../css/i/ixya7lsza.css';
import '../../css/b/bnugcub6t.css';
import '../../css/t/tk7619jch.css';
import '../../css/e/ehfhqhbzh.css';
import '../../css/r/rwv3vybdu.css';
import '../../css/t/t43n2bbii.css';
import '../../css/n/nmocvkbfm.css';
import '../../css/b/bko9nl3so.css';
import '../../css/g/gz56fkb1c.css';
import '../../css/q/qpd6wvb9g.css';
import '../../css/o/ohlogabfp.css';
import '../../css/g/gvkjly-0x.css';
import '../../css/t/t-sl1ccbz.css';
import '../../css/f/fvec-mbpl.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":48,"height":48};
const content = `<path class="rqjbujbsp"/><path class="qgnp5cb4r"/><path class="oc6dybb2z"/><path class="p7i62-78n"/><path class="vg8uzsbwa"/><path class="xgq0jdbhd"/><path class="g69d_nr1e"/><path class="lwlpgrwtk"/><path class="c9phsobye"/><path class="m97bqnbfn"/><path class="k_t9d4_st"/><path class="vf42t_jzt"/><path class="tjen39bmd"/><path class="om74372sc"/><path class="xxt_u1v2c"/><path class="rn4r82bfv"/><path class="hpuu0fjkz"/><path class="l-pxvfjlb"/><path class="dgodczr8q"/><path class="yt8se8nvp"/><path class="qa7y2xbel"/><path class="qidc3g6bb"/><path class="gjs9uqbtg"/><path class="y56q-_xtz"/><path class="bnehyjtet"/><path class="c_nptzxdf"/><path class="fspf2cc8a"/><path class="zlm3ccb8x"/><path class="r9xhlokyl"/><path class="e-cc1bzdo"/><path class="fil80-1iq"/><path class="qrj6mpbxq"/><path class="zf-1i_aza"/><path class="tgy2kc8wp"/><path class="zvocteb3b"/><path class="g-a2uqe-h"/><path class="dkknsfbkd"/><path class="lqq952h4f"/><path class="juqt_zp2c"/><path class="fvg2_4frg"/><path class="unl3x5biv"/><path class="dnd41wbik"/><path class="naa-_fz9o"/><path class="ixya7lsza"/><path class="bnugcub6t"/><path class="tk7619jch"/><path class="ehfhqhbzh"/><path class="rwv3vybdu"/><path class="t43n2bbii"/><path class="nmocvkbfm"/><path class="bko9nl3so"/><path class="gz56fkb1c"/><path class="qpd6wvb9g"/><path class="ohlogabfp"/><path class="gvkjly-0x"/><path class="t-sl1ccbz"/><path class="fvec-mbpl"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="streamline-emojis:family-man-man-girl-girl-2" /></template>
