<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/n/n5uoyhb1n.css';
import '../../css/a/aaiwvbcqd.css';
import '../../css/k/kvwvuxb5k.css';
import '../../css/q/qdg4kfb2g.css';
import '../../css/y/yeh33ac3z.css';
import '../../css/j/j2gf4wbms.css';
import '../../css/t/t0lperlyf.css';
import '../../css/d/d7xx-lb9l.css';
import '../../css/h/hcfanxbwy.css';
import '../../css/g/gne2g3juq.css';
import '../../css/v/vjvkwd8tg.css';
import '../../css/i/i1tfezb9s.css';
import '../../css/k/k7fre1cva.css';
import '../../css/o/obcm9ccja.css';
import '../../css/f/ft_ig1-7u.css';
import '../../css/s/sx4u-0fqq.css';
import '../../css/w/wo-z35bir.css';
import '../../css/y/yfpdqkb-f.css';
import '../../css/w/wq6j-gb6g.css';
import '../../css/t/taqty_6fh.css';
import '../../css/t/tadoqbdif.css';
import '../../css/s/sz7iqm8ro.css';
import '../../css/q/q4yfakbao.css';
import '../../css/u/u55gln9aa.css';
import '../../css/t/t8i2qeb4w.css';
import '../../css/y/yco37db0k.css';
import '../../css/g/g4v_48bas.css';
import '../../css/h/h36rerbna.css';
import '../../css/a/ab2mj1bmb.css';
import '../../css/i/iecvwyb9x.css';
import '../../css/n/n345m716i.css';
import '../../css/v/v4z5xsweh.css';
import '../../css/c/ces-qu5cj.css';
import '../../css/f/f5y2eeydg.css';
import '../../css/w/wl7u5eb4y.css';
import '../../css/w/wt58c978k.css';
import '../../css/x/xah_bbc7y.css';
import '../../css/w/wiuipqqqh.css';
import '../../css/w/wciq_obev.css';
import '../../css/d/d2rcjy0_m.css';
import '../../css/q/qeok7ljuu.css';
import '../../css/h/h-uf8tb6y.css';
import '../../css/n/n254zt6-e.css';
import '../../css/f/fu1w1hkoj.css';
import '../../css/o/om0vzfbre.css';
import '../../css/h/h7-gxoxov.css';
import '../../css/d/djmmwu-sr.css';
import '../../css/c/cm0weq6xc.css';
import '../../css/v/v9ksp5ohk.css';
import '../../css/f/f2ay1sb0i.css';
import '../../css/h/h3z4sdb-i.css';
import '../../css/d/dggc4lb4y.css';
import '../../css/z/zr79mdb_k.css';
import '../../css/h/hfr_bbr2g.css';
import '../../css/j/jznanobbb.css';
import '../../css/x/xcr6oznmz.css';
import '../../css/b/bnxd01bhy.css';
import '../../css/z/z--7sob4e.css';
import '../../css/m/mtwxp7bdv.css';
import '../../css/s/sx03pj5hw.css';
import '../../css/v/vnrwjw7ni.css';
import '../../css/x/xsk473bfu.css';
import '../../css/h/hvfx-kbff.css';
import '../../css/c/cah2p1b1y.css';
import '../../css/w/wddzazb9e.css';
import '../../css/v/v6cl1yarc.css';
import '../../css/b/bi0yqe5pl.css';
import '../../css/d/d7bfh3bgu.css';
import '../../css/i/izp_ajb2n.css';
import '../../css/e/eqfn1osvn.css';
import '../../css/d/dyyrp-bjw.css';
import '../../css/h/hbsfsktfw.css';
import '../../css/h/hhac8q-4i.css';
import '../../css/q/qkia3kwly.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":640,"height":480};
const content = `<path class="n5uoyhb1n"/><path class="aaiwvbcqd"/><path class="kvwvuxb5k"/><path class="qdg4kfb2g"/><path class="yeh33ac3z"/><path class="j2gf4wbms"/><path class="t0lperlyf"/><path class="d7xx-lb9l"/><path class="hcfanxbwy"/><path class="gne2g3juq"/><path class="vjvkwd8tg"/><path class="i1tfezb9s"/><path class="k7fre1cva"/><path class="obcm9ccja"/><path class="ft_ig1-7u"/><path class="sx4u-0fqq"/><path class="wo-z35bir"/><path class="yfpdqkb-f"/><path class="wq6j-gb6g"/><path class="taqty_6fh"/><path class="tadoqbdif"/><path class="sz7iqm8ro"/><path class="q4yfakbao"/><path class="u55gln9aa"/><path class="t8i2qeb4w"/><path class="yco37db0k"/><path class="g4v_48bas"/><path class="h36rerbna"/><path class="ab2mj1bmb"/><path class="iecvwyb9x"/><path class="n345m716i"/><path class="v4z5xsweh"/><path class="ces-qu5cj"/><path class="f5y2eeydg"/><path class="wl7u5eb4y"/><path class="wt58c978k"/><path class="xah_bbc7y"/><path class="wiuipqqqh"/><path class="wciq_obev"/><path class="d2rcjy0_m"/><path class="qeok7ljuu"/><path class="h-uf8tb6y"/><path class="n254zt6-e"/><path class="fu1w1hkoj"/><path class="om0vzfbre"/><path class="h7-gxoxov"/><path class="djmmwu-sr"/><path class="cm0weq6xc"/><path class="v9ksp5ohk"/><path class="f2ay1sb0i"/><path class="h3z4sdb-i"/><path class="dggc4lb4y"/><path class="zr79mdb_k"/><path class="hfr_bbr2g"/><path class="jznanobbb"/><path class="xcr6oznmz"/><path class="bnxd01bhy"/><path class="z--7sob4e"/><path class="mtwxp7bdv"/><path class="sx03pj5hw"/><path class="vnrwjw7ni"/><path class="xsk473bfu"/><path class="hvfx-kbff"/><path class="cah2p1b1y"/><path class="wddzazb9e"/><path class="v6cl1yarc"/><path class="bi0yqe5pl"/><path class="d7bfh3bgu"/><path class="izp_ajb2n"/><path class="eqfn1osvn"/><path class="dyyrp-bjw"/><path class="hbsfsktfw"/><path class="hhac8q-4i"/><path class="qkia3kwly"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="flag:sh-ta-4x3" /></template>
