<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/y/yo9k0acsv.css';
import '../../css/l/l_1bybclw.css';
import '../../css/h/hql1i9bgp.css';
import '../../css/w/weej2qbbd.css';
import '../../css/b/bvaynhycf.css';
import '../../css/j/jbo_i5-0g.css';
import '../../css/n/nqacdhblt.css';
import '../../css/z/zkp7wub4v.css';
import '../../css/a/a_h18jjnh.css';
import '../../css/r/rtm6hwb5c.css';
import '../../css/e/erl94ibso.css';
import '../../css/i/i9-aq65zy.css';
import '../../css/r/rvgppwbwq.css';
import '../../css/v/vp2bcugem.css';
import '../../css/r/r_zgydoyx.css';
import '../../css/p/peb9nrbuq.css';
import '../../css/h/h8o3c349j.css';
import '../../css/i/i28oemb4w.css';
import '../../css/w/w2iib4bsb.css';
import '../../css/m/mc-ddmbix.css';
import '../../css/d/d2z9s4bmd.css';
import '../../css/k/ka3utnbop.css';
import '../../css/w/w2_om1h5z.css';
import '../../css/t/tqs-3kb9w.css';
import '../../css/d/dee38dbqb.css';
import '../../css/f/fv0ppjjtu.css';
import '../../css/c/ce6crsqbg.css';
import '../../css/t/t8n0p59rn.css';
import '../../css/l/l47b2dbbt.css';
import '../../css/u/uf5ne8bxp.css';
import '../../css/u/uskpotbll.css';
import '../../css/z/za05uxkbr.css';
import '../../css/b/by266ubut.css';
import '../../css/l/l00vw58zn.css';
import '../../css/a/a4kwgf5pj.css';
import '../../css/t/ts43n_bte.css';
import '../../css/y/ybbeqr0uy.css';
import '../../css/o/oy0hhxbsa.css';
import '../../css/s/sdacwwbke.css';
import '../../css/z/zc5sudkfq.css';
import '../../css/l/ln06o5b1p.css';
import '../../css/f/ff1pceszb.css';
import '../../css/e/eg77f0bzg.css';
import '../../css/j/j61kfbb6z.css';
import '../../css/v/vdm6ztbvc.css';
import '../../css/h/h7vz-jq_o.css';
import '../../css/r/r987j3bsg.css';
import '../../css/a/axkff629z.css';
import '../../css/a/aa2famhjl.css';
import '../../css/v/v-x4rbbuh.css';
import '../../css/f/f2d5t5ouf.css';
import '../../css/y/yfwbbnb6v.css';
import '../../css/q/qidtfib0f.css';
import '../../css/e/eubh7sbgh.css';
import '../../css/x/xm1bogono.css';
import '../../css/j/jq9epoble.css';
import '../../css/z/zxkuo9b4a.css';
import '../../css/l/lzmp1gb3k.css';
import '../../css/c/cetu00bks.css';
import '../../css/v/vo1xrjb1o.css';
import '../../css/m/mwfod_-ue.css';
import '../../css/h/hv9qsbcls.css';
import '../../css/p/pql59r7xp.css';
import '../../css/z/zgcgnpbku.css';
import '../../css/z/zphizzbeg.css';
import '../../css/l/lcpot533s.css';
import '../../css/b/bk82q6bci.css';
import '../../css/j/jvhlf3u5m.css';
import '../../css/c/ct9i12lba.css';
import '../../css/a/a-xnvmt8p.css';
import '../../css/g/grjit4xdg.css';
import '../../css/j/j-4yydz-i.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":512,"height":512};
const content = `<path class="yo9k0acsv"/><path class="l_1bybclw"/><path class="hql1i9bgp"/><path class="weej2qbbd"/><path class="bvaynhycf"/><path class="jbo_i5-0g"/><path class="nqacdhblt"/><path class="zkp7wub4v"/><path class="a_h18jjnh"/><path class="rtm6hwb5c"/><path class="erl94ibso"/><path class="i9-aq65zy"/><path class="rvgppwbwq"/><path class="vp2bcugem"/><path class="r_zgydoyx"/><path class="peb9nrbuq"/><path class="h8o3c349j"/><path class="i28oemb4w"/><path class="w2iib4bsb"/><path class="mc-ddmbix"/><path class="d2z9s4bmd"/><path class="ka3utnbop"/><path class="w2_om1h5z"/><path class="tqs-3kb9w"/><path class="dee38dbqb"/><path class="fv0ppjjtu"/><path class="ce6crsqbg"/><path class="t8n0p59rn"/><path class="l47b2dbbt"/><path class="uf5ne8bxp"/><path class="uskpotbll"/><path class="za05uxkbr"/><path class="by266ubut"/><path class="l00vw58zn"/><path class="a4kwgf5pj"/><path class="ts43n_bte"/><path class="ybbeqr0uy"/><path class="oy0hhxbsa"/><path class="sdacwwbke"/><path class="zc5sudkfq"/><path class="ln06o5b1p"/><path class="ff1pceszb"/><path class="eg77f0bzg"/><path class="j61kfbb6z"/><path class="vdm6ztbvc"/><path class="h7vz-jq_o"/><path class="r987j3bsg"/><path class="axkff629z"/><path class="aa2famhjl"/><path class="v-x4rbbuh"/><path class="f2d5t5ouf"/><path class="yfwbbnb6v"/><path class="qidtfib0f"/><path class="eubh7sbgh"/><path class="xm1bogono"/><path class="jq9epoble"/><path class="zxkuo9b4a"/><path class="lzmp1gb3k"/><path class="cetu00bks"/><path class="vo1xrjb1o"/><path class="mwfod_-ue"/><path class="hv9qsbcls"/><path class="pql59r7xp"/><path class="zgcgnpbku"/><path class="zphizzbeg"/><path class="lcpot533s"/><path class="bk82q6bci"/><path class="jvhlf3u5m"/><path class="ct9i12lba"/><path class="a-xnvmt8p"/><path class="grjit4xdg"/><path class="j-4yydz-i"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="selfhst:stump" /></template>
