<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/f/ft5dv1b6b.css';
import '../../css/p/pzfektr_q.css';
import '../../css/q/qtf2xxodx.css';
import '../../css/q/qu008sbhz.css';
import '../../css/r/rpr1nrihb.css';
import '../../css/b/bir38_g6y.css';
import '../../css/t/tv_eqhble.css';
import '../../css/i/irsmfr51i.css';
import '../../css/w/wyirwgz5u.css';
import '../../css/s/sr7yr1b8w.css';
import '../../css/b/bwrxw2pid.css';
import '../../css/k/knwhy1bwd.css';
import '../../css/v/vgt-hh43y.css';
import '../../css/q/qgsnp3bzn.css';
import '../../css/o/o6p8zv3no.css';
import '../../css/p/pft9xx7vi.css';
import '../../css/f/fecn22kic.css';
import '../../css/w/w8vaye9nw.css';
import '../../css/x/x6_q38d3f.css';
import '../../css/v/vrhqpqwaz.css';
import '../../css/c/ct5-eebdz.css';
import '../../css/t/t6qdr-b-p.css';
import '../../css/p/p7ki1g0cw.css';
import '../../css/q/qple6vuwg.css';
import '../../css/s/s2gozmbnu.css';
import '../../css/d/d8uwdfl5h.css';
import '../../css/p/p6f-nex1q.css';
import '../../css/z/z56ezdboi.css';
import '../../css/o/oh1v8j8me.css';
import '../../css/x/x5_8tmbzk.css';
import '../../css/i/i1bsm_3cc.css';
import '../../css/d/dycbgdcrt.css';
import '../../css/y/y5bx2x3oz.css';
import '../../css/q/qdk63wc7y.css';
import '../../css/v/vyw0akbcn.css';
import '../../css/u/uqk1edbvq.css';
import '../../css/q/qa5oie1it.css';
import '../../css/j/jzlwyjbgy.css';
import '../../css/y/y8fxi1ijf.css';
import '../../css/n/n8xahxfpp.css';
import '../../css/i/ivgv-ibpi.css';
import '../../css/h/hrh_lqiqx.css';
import '../../css/t/tmvvai99h.css';
import '../../css/n/n_0tmebtv.css';
import '../../css/c/c1db1ct1a.css';
import '../../css/k/kv229mzxu.css';
import '../../css/v/vs_xekbtg.css';
import '../../css/v/vvb4kccpy.css';
import '../../css/m/m97ofbyov.css';
import '../../css/q/q6y0upb4x.css';
import '../../css/y/ya547lbwc.css';
import '../../css/c/ch3ae-dwa.css';
import '../../css/z/z3y9d2byb.css';
import '../../css/o/od2z7hvdl.css';
import '../../css/j/jyp5y-zyq.css';
import '../../css/g/gr-zzrbas.css';
import '../../css/d/db0q8sbhx.css';
import '../../css/k/kqxzrsbuc.css';
import '../../css/n/n7sww8ntg.css';
import '../../css/p/pdqjsnbgp.css';
import '../../css/m/mojn8pbrr.css';
import '../../css/j/j_hynhb-o.css';
import '../../css/a/aismpwbmv.css';
import '../../css/r/rj94ipb1d.css';
import '../../css/z/zm-bmj5dm.css';
import '../../css/e/e8f5mg2aq.css';
import '../../css/k/k962r8bwa.css';
import '../../css/y/y2g6smbch.css';
import '../../css/r/r_9dzrbxo.css';
import '../../css/i/iwutbylni.css';
import '../../css/o/ohv9pfb8a.css';
import '../../css/k/k81-2vblb.css';
import '../../css/i/im4n_k_uc.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":301,"height":151};
const content = `<g class="ft5dv1b6b"><path class="pzfektr_q"/><path class="qtf2xxodx"/><path class="qu008sbhz"/><path class="rpr1nrihb"/><path class="bir38_g6y"/><path class="tv_eqhble"/><path class="irsmfr51i"/><path class="wyirwgz5u"/><path class="sr7yr1b8w"/><path class="bwrxw2pid"/><path class="knwhy1bwd"/><path class="vgt-hh43y"/><path class="qgsnp3bzn"/><path class="o6p8zv3no"/><path class="pft9xx7vi"/><path class="fecn22kic"/><path class="w8vaye9nw"/><path class="x6_q38d3f"/><path class="vrhqpqwaz"/><path class="ct5-eebdz"/><path class="t6qdr-b-p"/><path class="p7ki1g0cw"/><path class="qple6vuwg"/><path class="s2gozmbnu"/><path class="d8uwdfl5h"/><path class="p6f-nex1q"/><path class="z56ezdboi"/><path class="oh1v8j8me"/><path class="x5_8tmbzk"/><path class="i1bsm_3cc"/><path class="dycbgdcrt"/><path class="y5bx2x3oz"/><path class="qdk63wc7y"/><path class="vyw0akbcn"/><path class="uqk1edbvq"/><path class="qa5oie1it"/><ellipse transform="rotate(-88.991 152.175 68.18)" class="jzlwyjbgy"/><ellipse transform="rotate(-88.98 153.192 66.503)" class="y8fxi1ijf"/><ellipse transform="rotate(-88.991 151.562 66.48)" class="n8xahxfpp"/><ellipse transform="rotate(-88.986 151.926 65.265)" class="ivgv-ibpi"/><ellipse transform="rotate(-88.986 151.779 63.836)" class="hrh_lqiqx"/><ellipse transform="rotate(-88.98 150.007 65.523)" class="tmvvai99h"/><ellipse transform="rotate(-88.98 150.375 64.02)" class="n_0tmebtv"/><ellipse transform="rotate(-88.98 148.375 64.037)" class="c1db1ct1a"/><ellipse transform="rotate(-88.986 150.858 62.086)" class="kv229mzxu"/><ellipse transform="rotate(-88.98 149.17 62.3)" class="vs_xekbtg"/><ellipse transform="rotate(-88.991 146.6 64.096)" class="vvb4kccpy"/><ellipse transform="rotate(-88.98 147.028 63.235)" class="m97ofbyov"/><ellipse transform="rotate(-88.98 147.541 62.256)" class="q6y0upb4x"/><path class="ya547lbwc"/><path class="ch3ae-dwa"/><path class="z3y9d2byb"/><path class="od2z7hvdl"/><path class="jyp5y-zyq"/><path class="gr-zzrbas"/><path class="db0q8sbhx"/><path class="kqxzrsbuc"/><path class="n7sww8ntg"/><path class="pdqjsnbgp"/><path class="mojn8pbrr"/><path class="j_hynhb-o"/><path class="aismpwbmv"/><path class="rj94ipb1d"/><path class="zm-bmj5dm"/><path class="e8f5mg2aq"/><path class="k962r8bwa"/><path class="y2g6smbch"/><ellipse transform="rotate(-88.986 148.6 58.284)" class="r_9dzrbxo"/><ellipse transform="rotate(-110.341 145.27 60.858)" class="iwutbylni"/><circle transform="rotate(-88.974 148.54 58.214)" class="ohv9pfb8a"/><path class="k81-2vblb"/><circle transform="rotate(-93.141 145.055 59.355)" class="im4n_k_uc"/></g>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="cif:dm" /></template>
