<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/k/k89d1bbde.css';
import '../../css/y/yknsl_sbd.css';
import '../../css/a/ao4wf5xhj.css';
import '../../css/r/rff22-aul.css';
import '../../css/r/r52orccfa.css';
import '../../css/d/dj1naxhpe.css';
import '../../css/p/p3gp_cf0g.css';
import '../../css/r/rf_mnabqw.css';
import '../../css/n/na6hww-bx.css';
import '../../css/v/vvxz9sped.css';
import '../../css/m/m9dt5yb6k.css';
import '../../css/p/pz-4oxbmn.css';
import '../../css/t/t31uwl1tx.css';
import '../../css/f/f1u9dh-dd.css';
import '../../css/c/cu80c0zjl.css';
import '../../css/m/m077etqzi.css';
import '../../css/v/v--_s4lvt.css';
import '../../css/u/ubiutteys.css';
import '../../css/y/yyxbw8ngo.css';
import '../../css/d/dlw6gxbqu.css';
import '../../css/n/nei-qbi6f.css';
import '../../css/k/k6yh70bpk.css';
import '../../css/n/nc01_6lmm.css';
import '../../css/k/kzm-pmbas.css';
import '../../css/u/u6n-q_ism.css';
import '../../css/o/o9akc_w8k.css';
import '../../css/h/hckpsacta.css';
import '../../css/v/vdo9vs6hn.css';
import '../../css/y/yqw9hxb-e.css';
import '../../css/l/lqir2lnii.css';
import '../../css/w/w7eavkbtz.css';
import '../../css/i/ilng70_pc.css';
import '../../css/b/bcxck0bvp.css';
import '../../css/q/qfk_6mlhg.css';
import '../../css/c/csye8xsmq.css';
import '../../css/a/aqdfubcsn.css';
import '../../css/o/owwkzcccn.css';
import '../../css/t/twtjfhb3y.css';
import '../../css/n/n_chvnbbb.css';
import '../../css/m/myl2edc_b.css';
import '../../css/d/d4v439n1r.css';
import '../../css/c/c52l1jp5x.css';
import '../../css/l/lq4le6bek.css';
import '../../css/t/tdrs5brbs.css';
import '../../css/v/vvtws1bmh.css';
import '../../css/g/g3ffezbrf.css';
import '../../css/x/xubl85f-c.css';
import '../../css/j/ja9dpvbra.css';
import '../../css/c/c27niqwuc.css';
import '../../css/b/bfmqggbry.css';
import '../../css/y/yafweko3q.css';
import '../../css/z/zz8mxzhzm.css';
import '../../css/k/kcrmj7jcb.css';
import '../../css/s/s_een6b4q.css';
import '../../css/u/ubyjdbbjy.css';
import '../../css/f/fks93bkvj.css';
import '../../css/b/bt2a7ab0w.css';
import '../../css/t/t1eyw-g2a.css';
import '../../css/u/u87dgqbtl.css';
import '../../css/h/hjoz-gbqm.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":512,"height":512};
const content = `<path class="k89d1bbde"/><path class="yknsl_sbd"/><path class="ao4wf5xhj"/><path class="rff22-aul"/><path class="r52orccfa"/><path class="dj1naxhpe"/><path class="p3gp_cf0g"/><path class="rf_mnabqw"/><path class="na6hww-bx"/><path class="vvxz9sped"/><path class="m9dt5yb6k"/><path class="pz-4oxbmn"/><path class="t31uwl1tx"/><path class="f1u9dh-dd"/><path class="cu80c0zjl"/><path class="m077etqzi"/><path class="v--_s4lvt"/><path class="ubiutteys"/><path class="yyxbw8ngo"/><path class="dlw6gxbqu"/><path class="nei-qbi6f"/><path class="k6yh70bpk"/><path class="nc01_6lmm"/><path class="kzm-pmbas"/><path class="u6n-q_ism"/><path class="o9akc_w8k"/><path class="hckpsacta"/><path class="vdo9vs6hn"/><path class="yqw9hxb-e"/><path class="lqir2lnii"/><path class="w7eavkbtz"/><path class="ilng70_pc"/><path class="bcxck0bvp"/><path class="qfk_6mlhg"/><path class="csye8xsmq"/><path class="aqdfubcsn"/><path class="owwkzcccn"/><path class="twtjfhb3y"/><path class="n_chvnbbb"/><path class="myl2edc_b"/><path class="d4v439n1r"/><path class="c52l1jp5x"/><path class="lq4le6bek"/><path class="tdrs5brbs"/><path class="vvtws1bmh"/><path class="g3ffezbrf"/><path class="xubl85f-c"/><path class="ja9dpvbra"/><path class="c27niqwuc"/><path class="bfmqggbry"/><path class="yafweko3q"/><path class="zz8mxzhzm"/><path class="kcrmj7jcb"/><path class="s_een6b4q"/><path class="ubyjdbbjy"/><path class="fks93bkvj"/><path class="bt2a7ab0w"/><path class="t1eyw-g2a"/><path class="u87dgqbtl"/><path class="hjoz-gbqm"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="flag:je-1x1" /></template>
