<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/g/gp649actv.css';
import '../../css/e/emi6f5bax.css';
import '../../css/v/vzbt5tbzr.css';
import '../../css/n/nf5la8h1n.css';
import '../../css/j/jixb39bqn.css';
import '../../css/q/qicoh0biy.css';
import '../../css/c/c10pj_bjn.css';
import '../../css/t/t9fnffbos.css';
import '../../css/i/i4ozuabzy.css';
import '../../css/t/t_sbzxblk.css';
import '../../css/x/xp14w-bcj.css';
import '../../css/g/gv_s5-b3n.css';
import '../../css/j/j49kc-bod.css';
import '../../css/l/lekm03lky.css';
import '../../css/c/c-3hnwhsi.css';
import '../../css/t/t3b281b-q.css';
import '../../css/i/i4vxjcc-s.css';
import '../../css/n/no0-kgbse.css';
import '../../css/x/xgbh7_bbb.css';
import '../../css/h/hxzoq5bgc.css';
import '../../css/b/bqlnszbbf.css';
import '../../css/g/g5p7jb0-m.css';
import '../../css/f/fd3tmotvj.css';
import '../../css/i/ikbbpubxu.css';
import '../../css/n/n2frtx_3l.css';
import '../../css/o/of244hmai.css';
import '../../css/d/dhg_fm12j.css';
import '../../css/q/qirhiyjfu.css';
import '../../css/h/h9i34pknq.css';
import '../../css/q/qg1kcbcpo.css';
import '../../css/r/rkj_9_g4l.css';
import '../../css/o/oxv6eli5z.css';
import '../../css/s/si-t5bcau.css';
import '../../css/p/p6rmrdbwt.css';
import '../../css/z/z1jshdbfq.css';
import '../../css/x/xhx9shznv.css';
import '../../css/r/r0g-z29dl.css';
import '../../css/w/w790glbok.css';
import '../../css/h/h3c8oibnh.css';
import '../../css/f/fe0ljmz8x.css';
import '../../css/f/fwdkmebez.css';
import '../../css/y/yggb_aczs.css';
import '../../css/q/q0is38bwj.css';
import '../../css/l/lx8yegbyf.css';
import '../../css/y/y4uwq7q9a.css';
import '../../css/y/y1zhmw_jj.css';
import '../../css/f/fp68niapu.css';
import '../../css/v/v5iu_9b6f.css';
import '../../css/r/rr0abi5cn.css';
import '../../css/d/d8de-vbdq.css';
import '../../css/k/kkbzz31dl.css';
import '../../css/a/anpottb0a.css';
import '../../css/w/wjmx_c-ey.css';
import '../../css/k/kid1c6bol.css';
import '../../css/n/nk_2_6b3p.css';
import '../../css/b/bxjwbublh.css';
import '../../css/z/ziv1nnbft.css';
import '../../css/i/i44vdsbwy.css';
import '../../css/u/u-bfw-b6m.css';
import '../../css/y/yhinoac-i.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":640,"height":480};
const content = `<path class="gp649actv"/><path class="emi6f5bax"/><path class="vzbt5tbzr"/><path class="nf5la8h1n"/><path class="jixb39bqn"/><path class="qicoh0biy"/><path class="c10pj_bjn"/><path class="t9fnffbos"/><path class="i4ozuabzy"/><path class="t_sbzxblk"/><path class="xp14w-bcj"/><path class="gv_s5-b3n"/><path class="j49kc-bod"/><path class="lekm03lky"/><path class="c-3hnwhsi"/><path class="t3b281b-q"/><path class="i4vxjcc-s"/><path class="no0-kgbse"/><path class="xgbh7_bbb"/><path class="hxzoq5bgc"/><path class="bqlnszbbf"/><path class="g5p7jb0-m"/><path class="fd3tmotvj"/><path class="ikbbpubxu"/><path class="n2frtx_3l"/><path class="of244hmai"/><path class="dhg_fm12j"/><path class="qirhiyjfu"/><path class="h9i34pknq"/><path class="qg1kcbcpo"/><path class="rkj_9_g4l"/><path class="oxv6eli5z"/><path class="si-t5bcau"/><path class="p6rmrdbwt"/><path class="z1jshdbfq"/><path class="xhx9shznv"/><path class="r0g-z29dl"/><path class="w790glbok"/><path class="h3c8oibnh"/><path class="fe0ljmz8x"/><path class="fwdkmebez"/><path class="yggb_aczs"/><path class="q0is38bwj"/><path class="lx8yegbyf"/><path class="y4uwq7q9a"/><path class="y1zhmw_jj"/><path class="fp68niapu"/><path class="v5iu_9b6f"/><path class="rr0abi5cn"/><path class="d8de-vbdq"/><path class="kkbzz31dl"/><path class="anpottb0a"/><path class="wjmx_c-ey"/><path class="kid1c6bol"/><path class="nk_2_6b3p"/><path class="bxjwbublh"/><path class="ziv1nnbft"/><path class="i44vdsbwy"/><path class="u-bfw-b6m"/><path class="yhinoac-i"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="flag:je-4x3" /></template>
