<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/e/ewy13re9a.css';
import '../../css/h/hcmu3s2pp.css';
import '../../css/a/asv5vac4a.css';
import '../../css/a/acw7wm4zd.css';
import '../../css/f/fene64byf.css';
import '../../css/n/n6w1xab6o.css';
import '../../css/f/f3o8f2bkx.css';
import '../../css/f/fjhljolry.css';
import '../../css/u/u0jr0lk0n.css';
import '../../css/t/tchtinb_v.css';
import '../../css/o/or7qhcbgg.css';
import '../../css/z/zh3iocc2z.css';
import '../../css/p/piwb7ps-r.css';
import '../../css/d/dton-sbsn.css';
import '../../css/f/f3e9pubtp.css';
import '../../css/w/wmfizqyxr.css';
import '../../css/c/c7r36gbjh.css';
import '../../css/h/h7ihqp0rs.css';
import '../../css/x/xfm4atg3c.css';
import '../../css/w/w7khb7b7l.css';
import '../../css/w/wccv0ebqo.css';
import '../../css/z/z0frz90xs.css';
import '../../css/q/qqxj7ybib.css';
import '../../css/a/amxepeoos.css';
import '../../css/b/b05y7dbcx.css';
import '../../css/h/hsn8ycbnv.css';
import '../../css/r/rfpdbjbhn.css';
import '../../css/j/jae25voir.css';
import '../../css/s/swvqv3b7e.css';
import '../../css/m/mkqsz1cxu.css';
import '../../css/d/dr-zfmbra.css';
import '../../css/q/qilp-4b5x.css';
import '../../css/n/nw3-rrben.css';
import '../../css/j/j3_8gk13n.css';
import '../../css/g/gpmdrqlzc.css';
import '../../css/g/gx8gw0b1k.css';
import '../../css/r/re866rbvq.css';
import '../../css/q/qjwxnobry.css';
import '../../css/z/zjyod_b9h.css';
import '../../css/l/lkmsszl8d.css';
import '../../css/f/fxbx3ybkl.css';
import '../../css/p/px5zzzb-j.css';
import '../../css/u/upicywg1b.css';
import '../../css/l/l64tfgdkt.css';
import '../../css/t/t343tnb_w.css';
import '../../css/n/n1569g5vc.css';
import '../../css/m/msf6bdaly.css';
import '../../css/u/u1_-r20ht.css';
import '../../css/w/wm122m-5n.css';
import '../../css/f/fsouz9hcl.css';
import '../../css/q/qn1daqipc.css';
import '../../css/e/evbzc3b5q.css';
import '../../css/p/p6srtm_ej.css';
import '../../css/i/i59ds2bje.css';
import '../../css/k/khca-pbse.css';
import '../../css/f/fg0maq1mn.css';
import '../../css/y/ybzg9gbxy.css';
import '../../css/i/id93h8b_t.css';
import '../../css/o/oqq_azbdo.css';
import '../../css/s/sq1sm2d-m.css';
import '../../css/q/qai9p8bfz.css';
import '../../css/p/pgjxuyjhj.css';
import '../../css/h/henq3fbcm.css';
import '../../css/t/tb6n7zbhc.css';
import '../../css/x/xsz09jbng.css';
import '../../css/u/uwdprpzeq.css';
import '../../css/p/pmf9mv88o.css';
import '../../css/y/ylm-2-bme.css';
import '../../css/y/y9fl-e6cu.css';
import '../../css/g/gferj4f-w.css';
import '../../css/r/rjpniljif.css';
import '../../css/l/liy652bup.css';
import '../../css/d/drzxmbe_n.css';
import '../../css/t/t34slyjiz.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":512,"height":512};
const content = `<path class="ewy13re9a"/><path class="hcmu3s2pp"/><path class="asv5vac4a"/><path class="acw7wm4zd"/><path class="fene64byf"/><path class="n6w1xab6o"/><path class="f3o8f2bkx"/><path class="fjhljolry"/><path class="u0jr0lk0n"/><path class="tchtinb_v"/><path class="or7qhcbgg"/><path class="zh3iocc2z"/><path class="piwb7ps-r"/><path class="dton-sbsn"/><path class="f3e9pubtp"/><path class="wmfizqyxr"/><path class="c7r36gbjh"/><path class="h7ihqp0rs"/><path class="xfm4atg3c"/><path class="w7khb7b7l"/><path class="wccv0ebqo"/><path class="z0frz90xs"/><path class="qqxj7ybib"/><path class="amxepeoos"/><path class="b05y7dbcx"/><path class="hsn8ycbnv"/><path class="rfpdbjbhn"/><path class="jae25voir"/><path class="swvqv3b7e"/><path class="mkqsz1cxu"/><path class="dr-zfmbra"/><path class="qilp-4b5x"/><path class="nw3-rrben"/><path class="j3_8gk13n"/><path class="gpmdrqlzc"/><path class="gx8gw0b1k"/><path class="re866rbvq"/><path class="qjwxnobry"/><path class="zjyod_b9h"/><path class="lkmsszl8d"/><path class="fxbx3ybkl"/><path class="px5zzzb-j"/><path class="upicywg1b"/><path class="l64tfgdkt"/><path class="t343tnb_w"/><path class="n1569g5vc"/><path class="msf6bdaly"/><path class="u1_-r20ht"/><path class="wm122m-5n"/><path class="fsouz9hcl"/><path class="qn1daqipc"/><path class="evbzc3b5q"/><path class="p6srtm_ej"/><path class="i59ds2bje"/><path class="khca-pbse"/><path class="fg0maq1mn"/><path class="ybzg9gbxy"/><path class="id93h8b_t"/><path class="oqq_azbdo"/><path class="sq1sm2d-m"/><path class="qai9p8bfz"/><path class="pgjxuyjhj"/><path class="henq3fbcm"/><path class="tb6n7zbhc"/><path class="xsz09jbng"/><path class="uwdprpzeq"/><path class="pmf9mv88o"/><path class="ylm-2-bme"/><path class="y9fl-e6cu"/><path class="gferj4f-w"/><path class="rjpniljif"/><path class="liy652bup"/><path class="drzxmbe_n"/><path class="t34slyjiz"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="flag:ta-1x1" /></template>
