<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/v/vc--wpv5i.css';
import '../../css/r/rhilikb3x.css';
import '../../css/r/r9fz9zwvj.css';
import '../../css/h/hg6_my1wq.css';
import '../../css/n/nng0vjblz.css';
import '../../css/a/a5yoi2bds.css';
import '../../css/q/qlree9g4f.css';
import '../../css/j/j5o0hdc4u.css';
import '../../css/w/w8ht-o0-z.css';
import '../../css/v/v4h2rdpeg.css';
import '../../css/d/ds8dneoas.css';
import '../../css/i/iu7mfxq2u.css';
import '../../css/k/kecm0wb1f.css';
import '../../css/a/a3z-kbc6q.css';
import '../../css/c/ckk580vgh.css';
import '../../css/p/plwy1enpf.css';
import '../../css/g/gu_3n_bwq.css';
import '../../css/x/xg3sa_15j.css';
import '../../css/f/fvf7s69ay.css';
import '../../css/l/lvupfmg4o.css';
import '../../css/b/bztf4yb1b.css';
import '../../css/f/f2lxo0v8q.css';
import '../../css/f/fw0p1qn5w.css';
import '../../css/d/d40-3hb1b.css';
import '../../css/e/ekrnv9bbf.css';
import '../../css/q/q001wd03m.css';
import '../../css/r/r21-70ymx.css';
import '../../css/s/sug-dtbzh.css';
import '../../css/g/geiu8-b0a.css';
import '../../css/l/lg6omwbvo.css';
import '../../css/o/o1ililbdg.css';
import '../../css/c/c3zq_ta8x.css';
import '../../css/q/qt1bj2b0y.css';
import '../../css/w/wzf04bbbn.css';
import '../../css/q/q2kmnfbfh.css';
import '../../css/u/uq5_3ugpi.css';
import '../../css/d/dc0se5b9t.css';
import '../../css/b/b2-kq_bke.css';
import '../../css/p/pehx4vbev.css';
import '../../css/d/djszuxb8c.css';
import '../../css/q/qcev6-97a.css';
import '../../css/o/on4gigb3h.css';
import '../../css/w/w647d2beq.css';
import '../../css/e/e6uz71-zk.css';
import '../../css/n/nyo3i5r-h.css';
import '../../css/q/qrfk6camy.css';
import '../../css/m/mbke2sbgv.css';
import '../../css/k/kjjunnbit.css';
import '../../css/j/jslyulcof.css';
import '../../css/t/tijf0ebim.css';
import '../../css/a/azu1qecwu.css';
import '../../css/b/bcfgxlhsw.css';
import '../../css/c/ce5igrowq.css';
import '../../css/e/eph0_lbmh.css';
import '../../css/r/rb-1gt_gh.css';
import '../../css/v/v1bkzyb6z.css';
import '../../css/q/q7eb_ijlr.css';
import '../../css/b/b04slhy0k.css';
import '../../css/w/wqopecbii.css';
import '../../css/r/re-gsqouc.css';
import '../../css/l/lnw76bcuc.css';
import '../../css/u/u2g50tbpl.css';
import '../../css/g/gluxp2bvz.css';
import '../../css/k/k_3aiabcy.css';
import '../../css/d/d-hdwbb2l.css';
import '../../css/b/bfen5qblt.css';
import '../../css/f/f0m67g_7p.css';
import '../../css/x/x-6_ibhnj.css';
import '../../css/n/nfrd6yudo.css';
import '../../css/y/yulrxlbtu.css';
import '../../css/s/stui2mbih.css';
import '../../css/j/jzs1yccrm.css';
import '../../css/u/uyve3j6-n.css';
import '../../css/b/bigfs689g.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":64,"height":64};
const content = `<linearGradient id="SVGQvNhDe4s" x1="114" x2="162" y1="-142.9" y2="-183.1" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset="0" class="vc--wpv5i"/><stop offset=".1" class="rhilikb3x"/><stop offset=".1" class="r9fz9zwvj"/><stop offset=".2" class="hg6_my1wq"/><stop offset=".2" class="nng0vjblz"/><stop offset=".3" class="a5yoi2bds"/><stop offset=".3" class="qlree9g4f"/><stop offset=".4" class="j5o0hdc4u"/><stop offset=".5" class="w8ht-o0-z"/><stop offset=".6" class="v4h2rdpeg"/><stop offset=".7" class="ds8dneoas"/><stop offset=".8" class="iu7mfxq2u"/><stop offset="1" class="kecm0wb1f"/></linearGradient><path fill="url(#SVGQvNhDe4s)" class="a3z-kbc6q"/><linearGradient id="SVGfnCo7cyg" x1="115.47" x2="160.47" y1="-144.06" y2="-181.86" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset="0" class="ckk580vgh"/><stop offset=".2" class="plwy1enpf"/><stop offset=".5" class="gu_3n_bwq"/><stop offset=".5" class="xg3sa_15j"/><stop offset=".7" class="fvf7s69ay"/><stop offset=".8" class="lvupfmg4o"/><stop offset=".8" class="bztf4yb1b"/><stop offset="1" class="f2lxo0v8q"/></linearGradient><path fill="url(#SVGfnCo7cyg)" class="fw0p1qn5w"/><linearGradient id="SVG2fqj9btM" x1="1933.73" x2="1955.63" y1="-176.94" y2="-237.14" gradientTransform="matrix(-1 0 0 1 1976.672 239.007)" gradientUnits="userSpaceOnUse"><stop offset="0" class="d40-3hb1b"/><stop offset=".1" class="ekrnv9bbf"/><stop offset=".3" class="q001wd03m"/><stop offset=".5" class="r21-70ymx"/><stop offset=".7" class="sug-dtbzh"/><stop offset=".8" class="geiu8-b0a"/><stop offset="1" class="lg6omwbvo"/></linearGradient><path fill="url(#SVG2fqj9btM)" class="o1ililbdg"/><path class="c3zq_ta8x"/><linearGradient id="SVGZux23clG" x1="124.2" x2="151.8" y1="-139.1" y2="-186.9" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset="0" class="d40-3hb1b"/><stop offset=".1" class="ekrnv9bbf"/><stop offset=".3" class="q001wd03m"/><stop offset=".5" class="r21-70ymx"/><stop offset=".7" class="sug-dtbzh"/><stop offset=".8" class="geiu8-b0a"/><stop offset="1" class="lg6omwbvo"/></linearGradient><path fill="url(#SVGZux23clG)" class="qt1bj2b0y"/><path class="wzf04bbbn"/><path class="q2kmnfbfh"/><linearGradient id="SVGcHPTUbKa" x1="150.49" x2="148.79" y1="-170.39" y2="-173.19" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset="0" class="uq5_3ugpi"/><stop offset="1" class="dc0se5b9t"/></linearGradient><path fill="url(#SVGcHPTUbKa)" class="b2-kq_bke"/><path class="pehx4vbev"/><path class="djszuxb8c"/><path class="qcev6-97a"/><path class="on4gigb3h"/><path class="w647d2beq"/><linearGradient id="SVG10BSLpgr" x1="145.58" x2="142.78" y1="-160.11" y2="-155.61" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset=".1" class="e6uz71-zk"/><stop offset=".9" class="nyo3i5r-h"/></linearGradient><path fill="url(#SVG10BSLpgr)" class="qrfk6camy"/><linearGradient id="SVG0bZkeYUj" x1="137.98" x2="133.78" y1="-167.34" y2="-168.54" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset=".2" class="e6uz71-zk"/><stop offset=".9" class="nyo3i5r-h"/></linearGradient><path fill="url(#SVG0bZkeYUj)" class="mbke2sbgv"/><linearGradient id="SVG5ppBudKB" x1="126.79" x2="126.19" y1="-172.9" y2="-171.4" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset="0" class="e6uz71-zk"/><stop offset=".1" class="e6uz71-zk"/><stop offset="1" class="nyo3i5r-h"/></linearGradient><path fill="url(#SVG5ppBudKB)" class="kjjunnbit"/><linearGradient id="SVGKAiat2zA" x1="141.6" x2="138.2" y1="-148.21" y2="-148.61" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset=".3" class="e6uz71-zk"/><stop offset=".3" class="e6uz71-zk"/><stop offset=".8" class="nyo3i5r-h"/></linearGradient><path fill="url(#SVGKAiat2zA)" class="jslyulcof"/><linearGradient id="SVGe1bowcLs" x1="141.71" x2="139.41" y1="-148.16" y2="-148.46" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset=".4" class="uq5_3ugpi"/><stop offset="1" class="tijf0ebim"/></linearGradient><path fill="url(#SVGe1bowcLs)" class="jslyulcof"/><linearGradient id="SVGRXLvpeWL" x1="105.64" x2="133.54" y1="-163.83" y2="-179.93" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset="0" class="azu1qecwu"/><stop offset="0" class="bcfgxlhsw"/><stop offset=".1" class="uq5_3ugpi"/></linearGradient><path fill="url(#SVGRXLvpeWL)" class="ce5igrowq"/><linearGradient id="SVGIALcBdUt" x1="137.95" x2="137.95" y1="-168.4" y2="-163.6" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset=".3" class="eph0_lbmh"/><stop offset="1" class="rb-1gt_gh"/></linearGradient><path fill="url(#SVGIALcBdUt)" class="v1bkzyb6z"/><linearGradient id="SVG8LkPpd6Z" x1="153.65" x2="153.65" y1="-133.3" y2="-194.3" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset="0" class="bztf4yb1b"/><stop offset="0" class="q7eb_ijlr"/><stop offset="0" class="b04slhy0k"/><stop offset="0" class="wqopecbii"/><stop offset="0" class="re-gsqouc"/><stop offset="0" class="lnw76bcuc"/><stop offset=".2" class="plwy1enpf"/><stop offset=".5" class="uq5_3ugpi"/><stop offset=".8" class="plwy1enpf"/><stop offset="1" class="iu7mfxq2u"/></linearGradient><path fill="url(#SVG8LkPpd6Z)" class="u2g50tbpl"/><linearGradient id="SVG0uUyDbOX" x1="138" x2="138.3" y1="-131.7" y2="-131.7" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset="0" class="bztf4yb1b"/><stop offset="0" class="q7eb_ijlr"/><stop offset="0" class="b04slhy0k"/><stop offset="0" class="wqopecbii"/><stop offset="0" class="re-gsqouc"/><stop offset="0" class="lnw76bcuc"/><stop offset=".2" class="plwy1enpf"/><stop offset=".5" class="uq5_3ugpi"/><stop offset=".8" class="plwy1enpf"/><stop offset="1" class="iu7mfxq2u"/></linearGradient><path fill="url(#SVG0uUyDbOX)" class="gluxp2bvz"/><linearGradient id="SVGjT5XveKc" x1="163.29" x2="149.79" y1="-139.09" y2="-158.89" gradientTransform="matrix(1 0 0 -1 -106 -131)" gradientUnits="userSpaceOnUse"><stop offset=".7" class="uq5_3ugpi"/><stop offset=".7" class="k_3aiabcy"/><stop offset=".7" class="d-hdwbb2l"/><stop offset=".7" class="bfen5qblt"/><stop offset=".8" class="f0m67g_7p"/><stop offset=".8" class="x-6_ibhnj"/><stop offset=".8" class="nfrd6yudo"/><stop offset=".8" class="yulrxlbtu"/><stop offset=".8" class="stui2mbih"/></linearGradient><path fill="url(#SVGjT5XveKc)" class="jzs1yccrm"/><path class="uyve3j6-n"/><path class="bigfs689g"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="thesvg-color:mercedes-benz" /></template>
