<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/u/u6ybmc7zi.css';
import '../../css/q/qpn8ndy_m.css';
import '../../css/t/t53b5ubxr.css';
import '../../css/g/gr1x3ab4p.css';
import '../../css/l/la1q1sbut.css';
import '../../css/h/hfymdzb1v.css';
import '../../css/t/t1taq9ntr.css';
import '../../css/e/edfjbprhv.css';
import '../../css/i/i3wmvrldz.css';
import '../../css/h/h-s4b8btd.css';
import '../../css/m/muo-14scy.css';
import '../../css/v/v18c9fbau.css';
import '../../css/i/ixp1rnuvx.css';
import '../../css/h/h3faswjbd.css';
import '../../css/d/dghab4mge.css';
import '../../css/d/d9bp0mb_d.css';
import '../../css/p/p7metl7rz.css';
import '../../css/k/k0nnd_b1n.css';
import '../../css/d/dfmpsf60n.css';
import '../../css/r/r_1x-8bol.css';
import '../../css/w/wc5vawbit.css';
import '../../css/i/ibn0cfbiz.css';
import '../../css/v/vh8shv2jd.css';
import '../../css/i/ib5-6nb8g.css';
import '../../css/x/xpwxubbim.css';
import '../../css/n/nceep6bpq.css';
import '../../css/l/l7qy0mbwo.css';
import '../../css/d/dop6zcbdp.css';
import '../../css/v/vz1k5jb5h.css';
import '../../css/r/rufvpde6e.css';
import '../../css/v/v_d738b7b.css';
import '../../css/m/mgbs9-x_r.css';
import '../../css/m/mw-4uw0wu.css';
import '../../css/s/s3e_mbepa.css';
import '../../css/f/f1pcvtpxd.css';
import '../../css/a/a0v8gvbay.css';
import '../../css/u/ugkk1hb4m.css';
import '../../css/f/fm4a60bny.css';
import '../../css/e/e0xiegz5t.css';
import '../../css/n/ncdyacnnu.css';
import '../../css/q/q931vccek.css';
import '../../css/d/dk5n9_bhg.css';
import '../../css/q/qc23mn10z.css';
import '../../css/x/xk0b_ol2y.css';
import '../../css/f/flpajlbgd.css';
import '../../css/f/f7mr51brt.css';
import '../../css/o/ojcl3cbpy.css';
import '../../css/l/lu3vzjbgc.css';
import '../../css/i/iy4dz1btr.css';
import '../../css/u/u2gepw84c.css';
import '../../css/r/r_4ku1dzo.css';
import '../../css/s/s4o1m2bvi.css';
import '../../css/g/g_g2h6b1w.css';
import '../../css/k/k00xu3srb.css';
import '../../css/c/cpcp4pbzv.css';
import '../../css/m/mhjvb-h2k.css';
import '../../css/o/okaoqhb4o.css';
import '../../css/a/a9e9x3vlp.css';
import '../../css/m/m5qd5zboo.css';
import '../../css/l/lqze_bf1u.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":640,"height":480};
const content = `<defs><linearGradient id="SVGdHCHJg4a" x1="498.7" x2="500.6" y1="289.1" y2="283.4" gradientUnits="userSpaceOnUse"><stop offset="0" class="u6ybmc7zi"/><stop offset=".3" class="qpn8ndy_m"/><stop offset="1" class="t53b5ubxr"/></linearGradient><linearGradient id="SVGlfi3vbwa" x1="501.4" x2="502.9" y1="291.4" y2="287.4" gradientUnits="userSpaceOnUse"><stop offset="0" class="gr1x3ab4p"/><stop offset="1" class="la1q1sbut"/></linearGradient><linearGradient id="SVGt6K66cYc" x1="484.8" x2="484.8" y1="311.7" y2="317.6" gradientUnits="userSpaceOnUse"><stop offset="0" class="hfymdzb1v"/><stop offset="1" class="t1taq9ntr"/></linearGradient><linearGradient id="SVG5CpW9d1X"><stop offset="0" class="edfjbprhv"/><stop offset=".5" class="i3wmvrldz"/><stop offset="1" class="edfjbprhv"/></linearGradient><linearGradient id="SVG1xW6SpNY" x1="444.5" x2="634.4" y1="317.5" y2="317.5" gradientUnits="userSpaceOnUse" href="#SVG5CpW9d1X"/><linearGradient id="SVGqORrzd7A" x1="484.8" x2="484.8" y1="311.7" y2="317.6" gradientUnits="userSpaceOnUse" href="#SVGt6K66cYc"/><linearGradient id="SVGjSwwXdRc" x1="98.9" x2="125" y1="1440.2" y2="1440.2" gradientTransform="scale(4.45715 .22436)" gradientUnits="userSpaceOnUse" href="#SVG5CpW9d1X"/><linearGradient id="SVGDd4sRcyr" x1="47.9" x2="61.7" y1="3054.2" y2="3054.2" gradientTransform="scale(9.12405 .1096)" gradientUnits="userSpaceOnUse" href="#SVG5CpW9d1X"/><clipPath id="SVGiokp8bOh"><path class="h-s4b8btd"/></clipPath></defs><path class="muo-14scy"/><path class="v18c9fbau"/><path class="ixp1rnuvx"/><g clip-path="url(#SVGiokp8bOh)" transform="translate(-80)scale(.8)"><path class="h3faswjbd"/><g id="SVGQbJLgbBm"><g id="SVG5ByECcnL"><path class="dghab4mge"/><path class="d9bp0mb_d"/></g><use width="100%" height="100%" href="#SVG5ByECcnL" transform="rotate(72 500 285.5)"/><use width="100%" height="100%" href="#SVG5ByECcnL" transform="rotate(144 500 285.5)"/><use width="100%" height="100%" href="#SVG5ByECcnL" transform="rotate(-144 500 285.5)"/><use width="100%" height="100%" href="#SVG5ByECcnL" transform="rotate(-72 500 285.5)"/></g><use width="100%" height="100%" href="#SVGQbJLgbBm" transform="rotate(8 500 285.5)"/><use width="100%" height="100%" href="#SVGQbJLgbBm" transform="rotate(16 500 285.5)"/><use width="100%" height="100%" href="#SVGQbJLgbBm" transform="rotate(24 500 285.5)"/><use width="100%" height="100%" href="#SVGQbJLgbBm" transform="rotate(32 500 285.5)"/><use width="100%" height="100%" href="#SVGQbJLgbBm" transform="rotate(40 500 285.5)"/><use width="100%" height="100%" href="#SVGQbJLgbBm" transform="rotate(48 500 285.5)"/><use width="100%" height="100%" href="#SVGQbJLgbBm" transform="rotate(56 500 285.5)"/><use width="100%" height="100%" href="#SVGQbJLgbBm" transform="rotate(64 500 285.5)"/><path class="p7metl7rz"/><path class="k0nnd_b1n"/><path class="dfmpsf60n"/><path class="r_1x-8bol"/><path class="wc5vawbit"/><path class="ibn0cfbiz"/><path class="vh8shv2jd"/><path class="ib5-6nb8g"/><path class="xpwxubbim"/><path fill="url(#SVGdHCHJg4a)" class="nceep6bpq"/><path class="l7qy0mbwo"/><path fill="url(#SVGlfi3vbwa)" class="dop6zcbdp"/><path class="vz1k5jb5h"/><path class="rufvpde6e"/><g fill="url(#SVG1xW6SpNY)"><path class="v_d738b7b"/><g id="SVGl7YOCdZu" fill="url(#SVG1xW6SpNY)"><path id="SVG1NHf8dDH" fill="url(#SVG1xW6SpNY)" class="mgbs9-x_r"/><use width="100%" height="100%" y="-1.1" fill="url(#SVG1xW6SpNY)" href="#SVG1NHf8dDH"/><use width="100%" height="100%" y="-2.2" fill="url(#SVG1xW6SpNY)" href="#SVG1NHf8dDH"/></g><use width="100%" height="100%" y="-3.3" fill="url(#SVG1xW6SpNY)" href="#SVGl7YOCdZu"/><use width="100%" height="100%" y="-6.7" fill="url(#SVG1xW6SpNY)" href="#SVGl7YOCdZu"/><path fill="url(#SVG1xW6SpNY)" class="mw-4uw0wu"/><path fill="url(#SVG1xW6SpNY)" class="s3e_mbepa"/></g><g class="f1pcvtpxd"><g id="SVGDf2Ere7h"><path fill="url(#SVGqORrzd7A)" class="a0v8gvbay"/><path class="ugkk1hb4m"/><path class="fm4a60bny"/><path class="e0xiegz5t"/><path class="ncdyacnnu"/></g><use width="100%" height="100%" x="-15.3" href="#SVGDf2Ere7h"/><g class="q931vccek"><path fill="url(#SVGqORrzd7A)" class="dk5n9_bhg"/><path class="qc23mn10z"/><path class="xk0b_ol2y"/><path class="flpajlbgd"/><path class="f7mr51brt"/><path class="ojcl3cbpy"/><path class="lu3vzjbgc"/></g><g id="SVGBL3ezdfb"><path fill="url(#SVGqORrzd7A)" class="iy4dz1btr"/><path class="u2gepw84c"/><path class="r_4ku1dzo"/><path class="s4o1m2bvi"/><path class="g_g2h6b1w"/><path class="k00xu3srb"/></g><use width="100%" height="100%" x="-15.4" href="#SVGBL3ezdfb" class="q931vccek"/></g><path class="cpcp4pbzv"/><path fill="url(#SVGjSwwXdRc)" class="mhjvb-h2k"/><g id="SVGpD2zWANO"><path id="SVGJnHEzdUm" fill="url(#SVGDd4sRcyr)" class="okaoqhb4o"/><use width="100%" height="100%" y="-1.3" href="#SVGJnHEzdUm"/><use width="100%" height="100%" y="-2.6" href="#SVGJnHEzdUm"/></g><use width="100%" height="100%" y="-3.9" href="#SVGpD2zWANO"/><use width="100%" height="100%" y="-7.7" href="#SVGpD2zWANO"/><path class="a9e9x3vlp"/><path class="m5qd5zboo"/></g><path class="lqze_bf1u"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="flag:ni-4x3" /></template>
