<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/n/nv9qcacyl.css';
import '../../css/t/tgrq921at.css';
import '../../css/e/eyrc--b5n.css';
import '../../css/y/ydxcqqb2k.css';
import '../../css/y/yrar9lk2h.css';
import '../../css/c/c9oge4bng.css';
import '../../css/t/tv42mxbff.css';
import '../../css/n/nl8p9os5n.css';
import '../../css/o/oke6svbvk.css';
import '../../css/l/lrsavemdj.css';
import '../../css/q/qzzl11tvb.css';
import '../../css/z/zppo2ixnu.css';
import '../../css/m/m99pxzb2w.css';
import '../../css/a/ayhr8xnni.css';
import '../../css/u/u1d_x9b8w.css';
import '../../css/i/ird5bl7bp.css';
import '../../css/p/p52grxb1b.css';
import '../../css/f/flgx-obde.css';
import '../../css/k/kq01xswph.css';
import '../../css/p/ppiu4xb9c.css';
import '../../css/c/cto2pndtj.css';
import '../../css/k/kkkpwcbdu.css';
import '../../css/d/d4j-7hxnv.css';
import '../../css/i/ifpzb5b4y.css';
import '../../css/s/sbmzx2cpu.css';
import '../../css/y/y0alzbifd.css';
import '../../css/l/lapq08byy.css';
import '../../css/d/dmdjzmbjw.css';
import '../../css/e/ejbdxgbui.css';
import '../../css/h/huhpkxbjz.css';
import '../../css/d/dbvz1fdkl.css';
import '../../css/s/sraeh7beg.css';
import '../../css/j/j0qw6ebgu.css';
import '../../css/f/f9sa95r4d.css';
import '../../css/l/l4sajsbye.css';
import '../../css/f/f_i_bwtgw.css';
import '../../css/f/fkvlw32qp.css';
import '../../css/q/qunyi7j-i.css';
import '../../css/s/s_6-glbjy.css';
import '../../css/a/ae8zcdclt.css';
import '../../css/f/febh8nbcq.css';
import '../../css/h/h3l7o3oih.css';
import '../../css/m/mqvl_0bgr.css';
import '../../css/w/wo6n8wmda.css';
import '../../css/x/xhmuop6xt.css';
import '../../css/i/i0vbomeoz.css';
import '../../css/p/p1y0fu6vm.css';
import '../../css/z/zpc__2biv.css';
import '../../css/u/uz40--r3y.css';
import '../../css/g/gpvu7g4gx.css';
import '../../css/y/ycdzkcbyh.css';
import '../../css/m/msm3p5b-g.css';
import '../../css/k/k3ok-r4fd.css';
import '../../css/o/o-nib98aa.css';
import '../../css/o/o7261rbol.css';
import '../../css/m/mh3mcdbkk.css';
import '../../css/v/vvwfrg9np.css';
import '../../css/o/ozg8yb0jp.css';
import '../../css/g/gr-m1tboi.css';
import '../../css/t/t0shkfw3q.css';
import '../../css/s/snd15bw1h.css';
import '../../css/e/e9cewfb3p.css';
import '../../css/q/qsbmy6baq.css';
import '../../css/y/ysadbhf8k.css';
import '../../css/v/v-nukhbdh.css';
import '../../css/p/psmv04bov.css';
import '../../css/f/fpwg_mbtu.css';
import '../../css/e/euzszdwgo.css';
import '../../css/x/xv-9lywgm.css';
import '../../css/s/s-ttf6bew.css';
import '../../css/z/zxt65jbpm.css';
import '../../css/p/pijdezb_x.css';
import '../../css/u/uwd2ku8hb.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":640,"height":480};
const content = `<g class="nv9qcacyl"><path class="tgrq921at"/><path class="eyrc--b5n"/><path class="ydxcqqb2k"/></g><g transform="translate(1 27.3)scale(1.06346)" class="yrar9lk2h"><path class="c9oge4bng"/><path class="tv42mxbff"/><path class="nl8p9os5n"/><path class="oke6svbvk"/><path class="lrsavemdj"/><path class="qzzl11tvb"/><path class="zppo2ixnu"/><path class="m99pxzb2w"/><path class="ayhr8xnni"/><g id="SVGhNTKRcrr"><path class="u1d_x9b8w"/><path class="ird5bl7bp"/><path class="p52grxb1b"/><path class="flgx-obde"/><path class="kq01xswph"/><path class="ppiu4xb9c"/><path class="cto2pndtj"/><path class="kkkpwcbdu"/><path class="d4j-7hxnv"/><path class="ifpzb5b4y"/><path class="sbmzx2cpu"/><path class="y0alzbifd"/><path class="lapq08byy"/><path class="dmdjzmbjw"/><path class="ejbdxgbui"/><path class="huhpkxbjz"/><path class="dbvz1fdkl"/><path class="sraeh7beg"/><path class="j0qw6ebgu"/><path class="f9sa95r4d"/><path class="l4sajsbye"/><path class="f_i_bwtgw"/><path class="fkvlw32qp"/><path class="qunyi7j-i"/><path class="s_6-glbjy"/><path class="ae8zcdclt"/><path class="febh8nbcq"/><path class="h3l7o3oih"/><path class="mqvl_0bgr"/><path class="wo6n8wmda"/><path class="xhmuop6xt"/><path class="i0vbomeoz"/><path class="p1y0fu6vm"/><path class="zpc__2biv"/><path class="uz40--r3y"/><path class="gpvu7g4gx"/><path class="ycdzkcbyh"/><path class="msm3p5b-g"/><path class="k3ok-r4fd"/><path class="o-nib98aa"/><path class="o7261rbol"/><path class="mh3mcdbkk"/><path class="vvwfrg9np"/><path class="ozg8yb0jp"/><path class="gr-m1tboi"/></g><use width="100%" height="100%" x="-600" href="#SVGhNTKRcrr" transform="scale(-1 1)"/><g class="t0shkfw3q"><path class="snd15bw1h"/><path class="e9cewfb3p"/><path class="qsbmy6baq"/><path class="ysadbhf8k"/><path class="v-nukhbdh"/><path class="psmv04bov"/><path class="fpwg_mbtu"/><path class="euzszdwgo"/><path class="xv-9lywgm"/><path class="s-ttf6bew"/><path class="zxt65jbpm"/></g></g><path class="pijdezb_x"/><path class="uwd2ku8hb"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="flag:af-4x3" /></template>
