<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/f/fehws8bhc.css';
import '../../css/e/ek91cfbrq.css';
import '../../css/p/p9tnyvbgr.css';
import '../../css/p/pc92m7ppv.css';
import '../../css/g/g8w2qcklc.css';
import '../../css/j/j1x3iyq7o.css';
import '../../css/g/gaglqqvft.css';
import '../../css/w/wd122tbbc.css';
import '../../css/v/vwg04rbfn.css';
import '../../css/c/cjc5u9bcm.css';
import '../../css/z/ztvio7bzm.css';
import '../../css/q/q8wmnbxxj.css';
import '../../css/o/o8sypbcqk.css';
import '../../css/o/oowkdq-tw.css';
import '../../css/l/lnmhikv5a.css';
import '../../css/i/i9rri7b3g.css';
import '../../css/z/zu3ov9bmo.css';
import '../../css/e/ehz13ccrh.css';
import '../../css/l/l5f0kncks.css';
import '../../css/m/mxw-8nb4h.css';
import '../../css/s/ss-8rrlba.css';
import '../../css/r/rlgqrwban.css';
import '../../css/x/xwjk1bc1t.css';
import '../../css/u/uhuv1gscu.css';
import '../../css/o/o__r06osj.css';
import '../../css/y/y277-la6h.css';
import '../../css/b/bkumrmb2a.css';
import '../../css/g/g18oyhbci.css';
import '../../css/m/mz7h7ed6u.css';
import '../../css/d/dy2c54vvb.css';
import '../../css/c/czz2yhbwz.css';
import '../../css/r/r8z6vud0n.css';
import '../../css/z/zly2ajxhb.css';
import '../../css/p/pqescxb5e.css';
import '../../css/m/m4g9uxaxc.css';
import '../../css/k/k5zfqb04h.css';
import '../../css/z/zgzxk0wbt.css';
import '../../css/i/i4djiobgm.css';
import '../../css/l/lthcr8d9u.css';
import '../../css/h/hcue3xmju.css';
import '../../css/b/b1d-5jb0q.css';
import '../../css/y/ylnxgzblb.css';
import '../../css/l/l6130vbyh.css';
import '../../css/v/voqjycbxt.css';
import '../../css/r/raf3l2loz.css';
import '../../css/v/vgt8hjeyp.css';
import '../../css/f/f7rmvbcgf.css';
import '../../css/m/m-qj-neop.css';
import '../../css/h/h7ebgzbfg.css';
import '../../css/f/fbtjvebuh.css';
import '../../css/k/kqz50h0dv.css';
import '../../css/i/i9-7tuw3q.css';
import '../../css/k/k10pcg2wp.css';
import '../../css/y/ylzl0cssm.css';
import '../../css/c/cxr1f2bvx.css';
import '../../css/p/pc3-qqbas.css';
import '../../css/w/wr7vw5l9l.css';
import '../../css/s/s5exgubhe.css';
import '../../css/i/ibzjqjb1u.css';
import '../../css/z/zram35nau.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":24,"height":24};
const content = `<path class="fehws8bhc"/><path class="ek91cfbrq"/><path class="p9tnyvbgr"/><path class="pc92m7ppv"/><path class="g8w2qcklc"/><path class="j1x3iyq7o"/><path class="gaglqqvft"/><path class="wd122tbbc"/><path class="vwg04rbfn"/><path class="cjc5u9bcm"/><path class="ztvio7bzm"/><path class="q8wmnbxxj"/><path class="o8sypbcqk"/><path class="oowkdq-tw"/><path class="lnmhikv5a"/><path class="i9rri7b3g"/><path class="zu3ov9bmo"/><path class="ehz13ccrh"/><path class="l5f0kncks"/><path class="mxw-8nb4h"/><path class="ss-8rrlba"/><path class="rlgqrwban"/><path class="xwjk1bc1t"/><path class="uhuv1gscu"/><path class="o__r06osj"/><path class="y277-la6h"/><path class="bkumrmb2a"/><path class="g18oyhbci"/><path class="mz7h7ed6u"/><path class="dy2c54vvb"/><path class="czz2yhbwz"/><path class="r8z6vud0n"/><path class="zly2ajxhb"/><path class="pqescxb5e"/><path class="m4g9uxaxc"/><path class="k5zfqb04h"/><path class="zgzxk0wbt"/><path class="i4djiobgm"/><path class="lthcr8d9u"/><path class="hcue3xmju"/><path class="b1d-5jb0q"/><path class="ylnxgzblb"/><path class="l6130vbyh"/><path class="voqjycbxt"/><path class="raf3l2loz"/><path class="vgt8hjeyp"/><path class="f7rmvbcgf"/><path class="m-qj-neop"/><path class="h7ebgzbfg"/><path class="fbtjvebuh"/><path class="kqz50h0dv"/><path class="i9-7tuw3q"/><path class="k10pcg2wp"/><path class="ylzl0cssm"/><path class="cxr1f2bvx"/><path class="pc3-qqbas"/><path class="wr7vw5l9l"/><path class="s5exgubhe"/><path class="ibzjqjb1u"/><path class="zram35nau"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="thesvg-color:aionlabs" /></template>
