<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/u/u77am4cpl.css';
import '../../css/h/hz56rjbux.css';
import '../../css/x/xdmt1vbqu.css';
import '../../css/l/l02qjnfpj.css';
import '../../css/t/t1ba2rbii.css';
import '../../css/r/rh6d1ijhx.css';
import '../../css/g/gjscsjj1y.css';
import '../../css/y/y2oakessq.css';
import '../../css/p/pmkbsmb0f.css';
import '../../css/x/xrifbk_lp.css';
import '../../css/f/f8fx8sjas.css';
import '../../css/x/xd2xklb1i.css';
import '../../css/x/xlj58ytku.css';
import '../../css/v/vp8q_3f-a.css';
import '../../css/n/nhqag_u4f.css';
import '../../css/l/le30fw4jw.css';
import '../../css/q/q-5z8cbah.css';
import '../../css/t/t0av-ib6t.css';
import '../../css/a/alih6isiu.css';
import '../../css/o/ojazmppug.css';
import '../../css/t/tn-488boq.css';
import '../../css/w/w6x7e3a9b.css';
import '../../css/m/mx44_tqib.css';
import '../../css/u/u2-ladcoc.css';
import '../../css/e/eflpr62qa.css';
import '../../css/l/lrj5x3bfz.css';
import '../../css/e/e-yl64ypa.css';
import '../../css/x/xkl6qpbkl.css';
import '../../css/p/pw824mwmg.css';
import '../../css/s/snrjs_bpc.css';
import '../../css/e/enr00rbah.css';
import '../../css/l/l83ws2bfs.css';
import '../../css/e/epea9wbya.css';
import '../../css/h/hp-5mqxss.css';
import '../../css/j/j0u8y2baa.css';
import '../../css/a/afm3lzb6y.css';
import '../../css/o/o8yezxbzq.css';
import '../../css/z/zp2clwbrs.css';
import '../../css/o/oj48--o7r.css';
import '../../css/h/hepue7bjy.css';
import '../../css/j/j7vpi6b3a.css';
import '../../css/m/mhjximbcc.css';
import '../../css/k/k6ri2qb9t.css';
import '../../css/t/tvbtlab6o.css';
import '../../css/u/ui3kjy-_h.css';
import '../../css/x/xhdvhvbsd.css';
import '../../css/f/fzepueb3z.css';
import '../../css/u/ut1ne2sqz.css';
import '../../css/m/mt62f9b8b.css';
import '../../css/z/zs24xxbud.css';
import '../../css/n/n236pbc6m.css';
import '../../css/s/sjuji_byp.css';
import '../../css/s/s49gqobkf.css';
import '../../css/q/qgc7njq8m.css';
import '../../css/m/mnoj3bcgq.css';
import '../../css/e/enm6zhbqv.css';
import '../../css/n/nle5cjbqb.css';
import '../../css/n/n8i66naud.css';
import '../../css/h/h4an31blc.css';
import '../../css/k/ki2ylhosa.css';
import '../../css/a/aw_3i546k.css';
import '../../css/v/vqaicwbpo.css';
import '../../css/l/lpm_-pm9d.css';
import '../../css/m/miss42ljk.css';
import '../../css/f/fxypc9b4f.css';
import '../../css/n/n5clzmbsa.css';
import '../../css/g/gek-o1brj.css';
import '../../css/e/e4hcm9j4j.css';
import '../../css/v/vj8c_ebas.css';
import '../../css/c/cctslcc3m.css';
import '../../css/v/v43qnfluh.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":512,"height":512};
const content = `<path class="u77am4cpl"/><path class="hz56rjbux"/><path class="xdmt1vbqu"/><path class="l02qjnfpj"/><path class="t1ba2rbii"/><path class="rh6d1ijhx"/><path class="gjscsjj1y"/><path class="y2oakessq"/><path class="pmkbsmb0f"/><path class="xrifbk_lp"/><path class="f8fx8sjas"/><path class="xd2xklb1i"/><path class="xlj58ytku"/><path class="vp8q_3f-a"/><path class="nhqag_u4f"/><path class="le30fw4jw"/><path class="q-5z8cbah"/><path class="t0av-ib6t"/><path class="alih6isiu"/><path class="ojazmppug"/><path class="tn-488boq"/><path class="w6x7e3a9b"/><path class="mx44_tqib"/><path class="u2-ladcoc"/><path class="eflpr62qa"/><path class="lrj5x3bfz"/><path class="e-yl64ypa"/><path class="xkl6qpbkl"/><path class="pw824mwmg"/><path class="snrjs_bpc"/><path class="enr00rbah"/><path class="l83ws2bfs"/><path class="epea9wbya"/><path class="hp-5mqxss"/><path class="j0u8y2baa"/><path class="afm3lzb6y"/><path class="o8yezxbzq"/><path class="zp2clwbrs"/><path class="oj48--o7r"/><path class="hepue7bjy"/><path class="j7vpi6b3a"/><path class="mhjximbcc"/><path class="k6ri2qb9t"/><path class="tvbtlab6o"/><path class="ui3kjy-_h"/><path class="xhdvhvbsd"/><path class="fzepueb3z"/><path class="ut1ne2sqz"/><path class="mt62f9b8b"/><path class="zs24xxbud"/><path class="n236pbc6m"/><path class="sjuji_byp"/><path class="s49gqobkf"/><path class="qgc7njq8m"/><path class="mnoj3bcgq"/><path class="enm6zhbqv"/><path class="nle5cjbqb"/><path class="n8i66naud"/><path class="h4an31blc"/><path class="ki2ylhosa"/><path class="aw_3i546k"/><path class="vqaicwbpo"/><path class="lpm_-pm9d"/><path class="miss42ljk"/><path class="fxypc9b4f"/><path class="n5clzmbsa"/><path class="gek-o1brj"/><path class="e4hcm9j4j"/><path class="vj8c_ebas"/><path class="cctslcc3m"/><path class="v43qnfluh"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="flag:as-1x1" /></template>
