<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/n/nk9q-tp-o.css';
import '../../css/u/uvwlnthkg.css';
import '../../css/y/yoi21hbsx.css';
import '../../css/e/e2wmd6bxc.css';
import '../../css/i/i5j-atbcm.css';
import '../../css/m/mn0bqxbyq.css';
import '../../css/a/atssdybyz.css';
import '../../css/k/ktoi7obgl.css';
import '../../css/o/okiks8q2c.css';
import '../../css/v/v-f1-zb0c.css';
import '../../css/o/olb7ap9et.css';
import '../../css/w/wmued4b-p.css';
import '../../css/c/cnkrurb5t.css';
import '../../css/n/n9vtyabis.css';
import '../../css/t/tm9he-que.css';
import '../../css/n/no1ygwt0j.css';
import '../../css/y/yus50xniq.css';
import '../../css/t/te6aiqssz.css';
import '../../css/n/nzf3ryumr.css';
import '../../css/j/jmk_uzcom.css';
import '../../css/m/mvtzrghxi.css';
import '../../css/t/tc14xacyl.css';
import '../../css/w/wzncetbmo.css';
import '../../css/f/fqg_7359t.css';
import '../../css/r/rm15qxxmb.css';
import '../../css/t/taq1jjbxf.css';
import '../../css/h/hvlfkzblt.css';
import '../../css/n/nsorq63pt.css';
import '../../css/o/o5oxwfb-l.css';
import '../../css/r/r5vy7jb-o.css';
import '../../css/x/x4nh-pb_e.css';
import '../../css/g/g9wm2ubtt.css';
import '../../css/v/vp1e2i0gy.css';
import '../../css/b/bsz8m7b8e.css';
import '../../css/y/yhtv720-r.css';
import '../../css/j/jaehzdbvh.css';
import '../../css/h/h9w-mus_i.css';
import '../../css/a/au51c6bso.css';
import '../../css/w/wdkmaibao.css';
import '../../css/o/oc7x6mbwd.css';
import '../../css/l/laliaw50f.css';
import '../../css/g/givgodbjp.css';
import '../../css/u/udpk_n1se.css';
import '../../css/d/dz_vajbwf.css';
import '../../css/l/lfffmzb_g.css';
import '../../css/t/t39mg6b7s.css';
import '../../css/w/w1zhfabhe.css';
import '../../css/l/lrnya0m8i.css';
import '../../css/d/dbepxhb5b.css';
import '../../css/k/k-mo4cchf.css';
import '../../css/b/b-o8bk9ly.css';
import '../../css/k/kgaf1eyez.css';
import '../../css/j/jzaypb8mk.css';
import '../../css/g/geyhmmbgi.css';
import '../../css/q/qgh8_lese.css';
import '../../css/l/l316xybyn.css';
import '../../css/l/ljrg5zb6y.css';
import '../../css/m/mpi3kjb4u.css';
import '../../css/i/iwdcaubid.css';
import '../../css/h/hsst8vsjd.css';
import '../../css/r/re26nobtr.css';
import '../../css/x/xrw9y_lgw.css';
import '../../css/c/cvpl_f_zm.css';
import '../../css/o/ot7q44boo.css';
import '../../css/s/sa80u147b.css';
import '../../css/w/wpl0bacgp.css';
import '../../css/n/nonsvbb_w.css';
import '../../css/a/av_f-4b1g.css';
import '../../css/a/a0qibtpje.css';
import '../../css/p/pdmp0e3pg.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":640,"height":480};
const content = `<path class="nk9q-tp-o"/><path class="uvwlnthkg"/><path class="yoi21hbsx"/><path class="e2wmd6bxc"/><path class="i5j-atbcm"/><path class="mn0bqxbyq"/><path class="atssdybyz"/><path class="ktoi7obgl"/><path class="okiks8q2c"/><path class="v-f1-zb0c"/><path class="olb7ap9et"/><path class="wmued4b-p"/><path class="cnkrurb5t"/><path class="n9vtyabis"/><path class="tm9he-que"/><path class="no1ygwt0j"/><path class="yus50xniq"/><path class="te6aiqssz"/><path class="nzf3ryumr"/><path class="jmk_uzcom"/><path class="mvtzrghxi"/><path class="tc14xacyl"/><path class="wzncetbmo"/><path class="fqg_7359t"/><path class="rm15qxxmb"/><path class="taq1jjbxf"/><path class="hvlfkzblt"/><path class="nsorq63pt"/><path class="o5oxwfb-l"/><path class="r5vy7jb-o"/><path class="x4nh-pb_e"/><path class="g9wm2ubtt"/><path class="vp1e2i0gy"/><path class="bsz8m7b8e"/><path class="yhtv720-r"/><path class="jaehzdbvh"/><path class="h9w-mus_i"/><path class="au51c6bso"/><path class="wdkmaibao"/><path class="oc7x6mbwd"/><path class="laliaw50f"/><path class="givgodbjp"/><path class="udpk_n1se"/><path class="dz_vajbwf"/><path class="lfffmzb_g"/><path class="t39mg6b7s"/><path class="w1zhfabhe"/><path class="lrnya0m8i"/><path class="dbepxhb5b"/><path class="k-mo4cchf"/><path class="b-o8bk9ly"/><path class="kgaf1eyez"/><path class="jzaypb8mk"/><path class="geyhmmbgi"/><path class="qgh8_lese"/><path class="l316xybyn"/><path class="ljrg5zb6y"/><path class="mpi3kjb4u"/><path class="iwdcaubid"/><path class="hsst8vsjd"/><path class="re26nobtr"/><path class="xrw9y_lgw"/><path class="cvpl_f_zm"/><path class="ot7q44boo"/><path class="sa80u147b"/><path class="wpl0bacgp"/><path class="nonsvbb_w"/><path class="av_f-4b1g"/><path class="a0qibtpje"/><path class="pdmp0e3pg"/>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="flag:as-4x3" /></template>
