<script setup>
import { Icon } from '@iconify/css-vue';
import '../../css/z/zrx75fq_y.css';
import '../../css/y/ymljeobsu.css';
import '../../css/s/se8vs5b7y.css';
import '../../css/p/pvk0wrb7l.css';
import '../../css/f/fdcwgl2hr.css';
import '../../css/x/x4-hzj80e.css';
import '../../css/k/kh-1bkbdk.css';
import '../../css/y/y66hika0x.css';
import '../../css/y/y53t1mbpu.css';
import '../../css/r/r8xbv7b2e.css';
import '../../css/q/q4ekysfnc.css';
import '../../css/x/xdj0cmb2w.css';
import '../../css/w/wt5dogb5t.css';
import '../../css/a/auiobx9dj.css';
import '../../css/i/ije-efbwt.css';
import '../../css/n/n_9435byh.css';
import '../../css/q/qu1tfsrhu.css';
import '../../css/s/sei6yi08w.css';
import '../../css/b/bq8oiubyh.css';
import '../../css/j/jv-vps9mp.css';
import '../../css/h/hgpq222do.css';
import '../../css/x/x7rdwqb8b.css';
import '../../css/r/rxdya6fqq.css';
import '../../css/s/s-t-d6bnj.css';
import '../../css/k/kn2lusbzp.css';
import '../../css/s/s2ulbubuq.css';
import '../../css/s/s7h_l9nqk.css';
import '../../css/f/fwdwo7b1p.css';
import '../../css/v/vkbznzbgw.css';
import '../../css/a/a77_jmino.css';
import '../../css/m/mq1kl_c9e.css';
import '../../css/n/n9r6vfogx.css';
import '../../css/n/noad19z0j.css';
import '../../css/r/rblgz6e3b.css';
import '../../css/e/evybj8mil.css';
import '../../css/x/xp29imb2e.css';
import '../../css/n/ni4c-2p5s.css';
import '../../css/d/dio_5eb4g.css';
import '../../css/g/gehqi91xl.css';
import '../../css/n/nwo8lib2d.css';
import '../../css/q/qwdw7_95r.css';
import '../../css/g/gb-uf3b_t.css';
import '../../css/f/fmyg8dbne.css';
import '../../css/i/ilexhybqp.css';
import '../../css/i/i7r9r9bve.css';
import '../../css/x/xmg8o9bai.css';
import '../../css/t/tfqr2ybqn.css';
import '../../css/h/hw51jrtgy.css';
import '../../css/f/ft5dv1b6b.css';
import '../../css/q/qbn2whouw.css';
import '../../css/w/wu4p3r6uz.css';
import '../../css/r/r7j9bcbay.css';
import '../../css/n/nlplllb1c.css';
import '../../css/c/cb6z136hc.css';
import '../../css/q/qiz2xabld.css';
import '../../css/j/jxqi2jbpi.css';
import '../../css/g/gucmk0b-x.css';
import '../../css/y/yi1hrkcct.css';
import '../../css/j/j0-99u2uf.css';
import '../../css/a/aktk25bum.css';
import '../../css/s/shm7pcckr.css';
import '../../css/v/vyuwk8b5m.css';
import '../../css/l/l527hrb0p.css';
import '../../css/k/kvgw_svyg.css';
import '../../css/d/dr5knb_lo.css';
import '../../css/s/smygkpvhn.css';
import '../../css/s/s8k97edxl.css';
import '../../css/a/a4z_nob0i.css';
import '../../css/e/evvkaklbc.css';
import '../../css/i/i_zwavv6b.css';
import '../../css/a/agzm5ebow.css';

const props = defineProps(["width","height"]);

const viewBox = {"width":640,"height":480};
const content = `<path class="zrx75fq_y"/><path class="ymljeobsu"/><path class="se8vs5b7y"/><path class="pvk0wrb7l"/><path class="fdcwgl2hr"/><path class="x4-hzj80e"/><g transform="translate(-306.8 -21.2)scale(.87136)" class="kh-1bkbdk"><use width="100%" height="100%" href="#SVGBoUu4buM"/><use width="100%" height="100%" href="#SVGj79F4dzO"/><use width="100%" height="100%" href="#SVGhyU6wb3D"/><use width="100%" height="100%" href="#SVG3kUlSbGI"/><use width="100%" height="100%" href="#SVG4ZEWxcIR"/><use width="100%" height="100%" href="#SVGxfpdu0NT"/><use width="100%" height="100%" href="#SVGI9YOodJy"/></g><g transform="translate(-306.8 -21.2)scale(.87136)" class="y66hika0x"><g id="SVGj79F4dzO" class="y53t1mbpu"><path class="r8xbv7b2e"/><path class="q4ekysfnc"/></g><path id="SVGhyU6wb3D" class="xdj0cmb2w"/><g class="wt5dogb5t"><path class="auiobx9dj"/><path class="ije-efbwt"/><path class="n_9435byh"/><path class="qu1tfsrhu"/></g></g><g transform="translate(-306.8 -21.2)scale(.87136)" class="y66hika0x"><g id="SVG3kUlSbGI" class="sei6yi08w"><path class="bq8oiubyh"/><path class="jv-vps9mp"/></g><g class="hgpq222do"><g id="SVGxfpdu0NT"><path class="x7rdwqb8b"/><path class="rxdya6fqq"/><path class="s-t-d6bnj"/><path class="kn2lusbzp"/><path class="s2ulbubuq"/><path class="s7h_l9nqk"/><path class="fwdwo7b1p"/><path class="vkbznzbgw"/></g><g id="SVGI9YOodJy"><path class="a77_jmino"/><path class="mq1kl_c9e"/><path class="n9r6vfogx"/><path class="noad19z0j"/><path class="rblgz6e3b"/><path class="evybj8mil"/><path class="xp29imb2e"/><path class="ni4c-2p5s"/><path class="dio_5eb4g"/><path class="gehqi91xl"/><path class="nwo8lib2d"/><path class="qwdw7_95r"/></g></g><g id="SVG4ZEWxcIR" class="gb-uf3b_t"><path class="fmyg8dbne"/><path class="ilexhybqp"/><path class="i7r9r9bve"/><g class="xmg8o9bai"><path class="tfqr2ybqn"/><path class="hw51jrtgy"/></g><g class="ft5dv1b6b"><path class="qbn2whouw"/><path class="wu4p3r6uz"/></g></g></g><g transform="translate(-306.8 -21.2)scale(.87136)" class="r7j9bcbay"><path id="SVGBoUu4buM" class="nlplllb1c"/><path class="cb6z136hc"/><path class="qiz2xabld"/><g class="jxqi2jbpi"><path class="gucmk0b-x"/><g class="ft5dv1b6b"><path class="yi1hrkcct"/><path class="j0-99u2uf"/><path class="aktk25bum"/><path class="shm7pcckr"/><path class="vyuwk8b5m"/><path class="l527hrb0p"/><path class="kvgw_svyg"/><path class="dr5knb_lo"/><path class="smygkpvhn"/></g><path class="s8k97edxl"/><path class="a4z_nob0i"/></g><g id="SVGkMr6RcKS"><path class="evvkaklbc"/><path class="i_zwavv6b"/></g><use width="100%" height="100%" x="90.1" href="#SVGkMr6RcKS"/><use width="100%" height="100%" x="45" y="52.2" href="#SVGkMr6RcKS"/><path class="agzm5ebow"/></g>`;
</script>
<template><Icon :width="width" :height="height" :viewBox="viewBox" :content="content" fallback="flag:ky-4x3" /></template>
